apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  # Lägg till ökad timeout
  timeout: 30m
  chart:
    spec:
      chart: loki-stack
      version: '2.10.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    loki:
      # Resource limits
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
      
      # Persistent storage
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
      
      # Node affinity to keep off master nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      
      # Loki configuration
      config:
        auth_enabled: false
        server:
          http_listen_port: 3100
        schema_config:
          configs:
            - from: "2020-10-24"  # Enkel datum-sträng med citattecken
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: index_
                period: 24h
        storage_config:
          filesystem:
            directory: /data/loki/chunks
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_entries_limit_per_query: 5000
          max_query_parallelism: 8
          # query_timeout borttagen för att undvika valideringsfel
        ingester:
          lifecycler:
            address: 127.0.0.1
            ring:
              kvstore:
                store: inmemory
              replication_factor: 1
            final_sleep: 0s
          chunk_idle_period: 5m
          chunk_retain_period: 30s
    
    # Promtail configuration
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      
      # Tolerations för att köra på alla noder, inklusive master/control-plane
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
          
      # SecurityContext för att ge rätt behörigheter
      securityContext:
        privileged: true
        runAsUser: 0  # Kör som root
        
      # Lägg till readiness probe med längre timeout
      readinessProbe:
        failureThreshold: 5
        httpGet:
          path: /ready
          port: http-metrics
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      
      # Använd standardvolymerna från Helm-diagrammet istället för att definiera egna
          
      config:
        lokiAddress: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_controller_name]
                  regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                  action: replace
                  target_label: __tmp_controller_name
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: app
                - action: replace
                  source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node_name
                - action: replace
                  source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - action: replace
                  source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - action: replace
                  source_labels: [__meta_kubernetes_pod_container_name]
                  target_label: container
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__
    
    # Aktivera Loki dashboards för att användas med extern Grafana
    grafana:
      enabled: false
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: loki
    
    # Aktivera dashboards
    dashboards:
      config:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          annotations: {}
          namespace: loki