apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  # Lägg till ökad timeout
  timeout: 30m
  chart:
    spec:
      chart: loki
      version: '2.9.1'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # Resource limits
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 600m
        memory: 1Gi
    
    # Persistent storage
    persistence:
      enabled: true
      storageClassName: rook-ceph-block
      size: 10Gi
    
    # Node affinity to keep off master nodes
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - "true"
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    
    # Loki configuration
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
          - from: 2020-09-01
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: loki_index_
              period: 24h

  # Installera Promtail separat
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring