apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '6.28.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # Deployment mode - use SingleBinary for simplicity
    deploymentMode: "SingleBinary"
    
    # Loki configuration
    loki:
      # Structured configuration for Loki
      commonConfig:
        replication_factor: 1
      auth_enabled: false
      # Configure schema and storage
      schemaConfig:
        configs:
          - from: "2023-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storageConfig:
        filesystem:
          directory: /var/loki/chunks
      # Configure limits
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        ingestion_rate_mb: 8
        ingestion_burst_size_mb: 16
        max_entries_limit_per_query: 5000
        max_query_parallelism: 8
        query_timeout: 3m
    
    # SingleBinary mode configuration
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
      # Node affinity to avoid master nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    
    # Disable gateway (not needed in singleBinary mode)
    gateway:
      enabled: false
    
    # Disable all other components (not needed in singleBinary mode)
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false
    ingester:
      enabled: false
    querier:
      enabled: false
    queryFrontend:
      enabled: false
    queryScheduler:
      enabled: false
    distributor:
      enabled: false
    compactor:
      enabled: false
    indexGateway:
      enabled: false
    
    # Disable MinIO since we're using filesystem storage
    minio:
      enabled: false
    
    # Promtail configuration for log collection
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      config:
        clients:
          - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_controller_name]
                  regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                  action: replace
                  target_label: __tmp_controller_name
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: app
                - action: replace
                  source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node_name
                - action: replace
                  source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - action: replace
                  source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - action: replace
                  source_labels: [__meta_kubernetes_pod_container_name]
                  target_label: container

    # Enable Grafana dashboards for Loki
    grafana:
      enabled: false  # Disable the bundled Grafana as we already have one