apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '5.41.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # Use monolithic deployment mode for simplicity
    deploymentMode: "SingleBinary"
    
    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
      # Node affinity to keep off master node
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    
    # Loki configuration
    loki:
      # Common Loki configuration
      commonConfig:
        replication_factor: 1
      
      # Schema configuration
      structuredConfig:
        auth_enabled: false
        
        schema_config:
          configs:
            - from: "2023-01-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        
        storage_config:
          filesystem:
            directory: /var/loki/chunks
        
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_entries_limit_per_query: 5000
          max_query_parallelism: 8
        
        query_range:
          align_queries_with_step: true
          max_retries: 5
          cache_results: true
          results_cache:
            cache:
              enable_fifocache: true
              fifocache:
                max_size_items: 1024
                validity: 24h
        
        frontend:
          max_outstanding_per_tenant: 2048
          compress_responses: true
        
        querier:
          max_concurrent: 8
          query_timeout: 3m
        
        ruler:
          enable_api: true
    
    # Gateway configuration
    gateway:
      enabled: true
      replicas: 1
      ingress:
        enabled: false
    
    # Disable components we don't need in monolithic mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    
    # Disable MinIO since we're using filesystem storage
    minio:
      enabled: false
    
    # Enable monitoring
    monitoring:
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false  # Assuming you already have it installed
    
    # Promtail configuration for log collection
    promtail:
      enabled: true
      # Resource limits for Promtail
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Configure Promtail to scrape all pods
      config:
        clients:
          - url: http://{{ .Release.Name }}-gateway:3100/loki/api/v1/push
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_controller_name
                  regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                  action: replace
                  target_label: __tmp_controller_name
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                    - __meta_kubernetes_pod_label_app
                    - __tmp_controller_name
                    - __meta_kubernetes_pod_name
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: app
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_component
                    - __meta_kubernetes_pod_label_component
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: component
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_node_name
                  target_label: node_name
                - action: replace
                  source_labels:
                  - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  replacement: $1
                  separator: /
                  source_labels:
                  - namespace
                  - app
                  target_label: job
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_container_name
                  target_label: container
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__
                - action: replace
                  regex: true/(.*)
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__

    # Enable Grafana dashboards for Loki
    grafana:
      enabled: false  # Disable the bundled Grafana as we already have one
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: loki