apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: '2.9.11'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    loki:
      # Resource limits with increased values to handle query load
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
      # Persistent storage using Rook-Ceph
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
        accessModes:
        - ReadWriteOnce
      # Node affinity to keep off master node
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      # We'll use a separate ingress resource instead of the built-in one
      ingress:
        enabled: false
      # Loki configuration with minimal query timeout settings
      config:
        auth_enabled: false
        chunk_store_config:
          max_look_back_period: 336h  # 14 days
        table_manager:
          retention_deletes_enabled: true
          retention_period: 336h  # 14 days
        schema_config:
          configs:
            - from: "2020-10-24"
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/index
            cache_location: /data/loki/index_cache
            cache_ttl: 24h
            shared_store: filesystem
          filesystem:
            directory: /data/loki/chunks
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h  # 7 days
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_entries_limit_per_query: 5000
          # Add these two settings to fix query timeout issues
          max_query_parallelism: 8
          query_timeout: 3m
    
    promtail:
      # Resource limits for Promtail
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      # Configure Promtail to scrape all pods
      config:
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_controller_name
                  regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                  action: replace
                  target_label: __tmp_controller_name
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                    - __meta_kubernetes_pod_label_app
                    - __tmp_controller_name
                    - __meta_kubernetes_pod_name
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: app
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_component
                    - __meta_kubernetes_pod_label_component
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: component
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_node_name
                  target_label: node_name
                - action: replace
                  source_labels:
                  - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  replacement: $1
                  separator: /
                  source_labels:
                  - namespace
                  - app
                  target_label: job
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_container_name
                  target_label: container
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__
                - action: replace
                  regex: true/(.*)
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__

    # Enable Grafana dashboards for Loki
    grafana:
      enabled: false  # Disable the bundled Grafana as we already have one
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: loki
