apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '5.41.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    # Use monolithic deployment mode for simplicity
    loki:
      commonConfig:
        replication_factor: 1
      
      structuredConfig:
        auth_enabled: false
        server:
          http_listen_port: 3100
          grpc_listen_port: 9096
        schema_config:
          configs:
            - from: "2023-01-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        storage_config:
          filesystem:
            directory: /var/loki/chunks
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 8
          ingestion_burst_size_mb: 16
          max_entries_limit_per_query: 5000
          max_query_parallelism: 8
          query_timeout: 3m
        
        # Query frontend config
        frontend:
          max_outstanding_per_tenant: 200
          compress_responses: true
        
        # Specify querier configuration
        querier:
          max_concurrent: 8
    
    # SingleBinary mode configuration
    singleBinary:
      replicas: 1
      nodeSelector: {}
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
        accessModes:
        - ReadWriteOnce
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
    
    # Pod affinity to avoid master nodes
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - "true"
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
    
    # Deployment mode
    deploymentMode: singleBinary
    
    # Disable gateway (not needed in singleBinary mode)
    gateway:
      enabled: false
    
    # Disable all other components (not needed in singleBinary mode)
    backend:
      enabled: false
    read:
      enabled: false
    write:
      enabled: false
    ingester:
      enabled: false
    querier:
      enabled: false
    queryFrontend:
      enabled: false
    queryScheduler:
      enabled: false
    distributor:
      enabled: false
    compactor:
      enabled: false
    indexGateway:
      enabled: false
    
    # Disable MinIO since we're using filesystem storage
    minio:
      enabled: false
    
    # Promtail configuration for log collection
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      config:
        clients:
          - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

    # Enable Grafana dashboards for Loki
    grafana:
      enabled: false  # Disable the bundled Grafana as we already have one