apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: '2.10.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    loki:
      # Resource limits
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 600m
          memory: 1Gi
      
      # Persistent storage
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        size: 10Gi
      
      # Node affinity to keep off master nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
      
      # Simplified Loki configuration
      config: {}
    
    # Promtail configuration
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      # Disable readiness probe to prevent pods from failing when no logs are found initially
      readinessProbe: null
      # Set livenessProbe to ensure pods are considered alive
      livenessProbe:
        httpGet:
          path: /ready
          port: http-metrics
        initialDelaySeconds: 10
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 5
      # Tolerations för att köra på alla noder, inklusive master/control-plane
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      config:
        lokiAddress: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
        # Skip existing files check to prevent readiness probe failures
        clients:
          - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
        snippets:
          extraScrapeConfigs: |
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_controller_name]
                  regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                  action: replace
                  target_label: __tmp_controller_name
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
                  regex: ^;*([^;]+)(;.*)?$
                  action: replace
                  target_label: app
                - action: replace
                  source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node_name
                - action: replace
                  source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - action: replace
                  source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - action: replace
                  source_labels: [__meta_kubernetes_pod_container_name]
                  target_label: container
    
    # Aktivera Loki dashboards för att användas med extern Grafana
    grafana:
      enabled: false
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: loki
    
    # Aktivera dashboards
    dashboards:
      config:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          annotations: {}
          namespace: loki