apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - namespace.yaml
  - helm-release.yaml
  - grafana-datasource.yaml
  - loki-dashboard.yaml
  - loki-ingress.yaml
