apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki
resources:
  - namespace.yaml
  - helm-release.yaml
  - loki-ingress.yaml

# Grafana-integration hanteras separat för att den ska hamna i monitoring-namnrymden
