apiVersion: v1
kind: Secret
metadata:
    labels:
        app.kubernetes.io/instance: basic-memory
        app.kubernetes.io/name: basic-memory
    name: basic-memory-auth
    namespace: basic-memory
stringData:
    users: ENC[AES256_GCM,data:hz8O9YEIhnc4XTzjhreunrUZ2SRLuMLedAp7l9BzzCS/oFHKlxZiLQ2nxCra4j7IpqF2r+0FAGvFAR7DCZi2cfQrtYrYSZgyCSE1DG0nxQm6E3/bWKPWSAl7yTClIdAnPeNkg9fYYrz0EG6wZ3F26uPx7QZV/VTNltexJiHi5LaSHDYilLw=,iv:qVZDZOEoJkQ58KIsCbgkZwg01w/j8IJRljrDtDdP0fI=,tag:NqKL6wi0nQhUr5GhMM3ZWA==,type:str]
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:53:51Z"
    mac: ENC[AES256_GCM,data:a7mIrBNm9dr4X5HeSL7j0RHb5fZFw2HQ4zRTY8pl1v3BjgrHl0RH3N3XL7gPbWXOUonpNYi6vGzyNRiLDpJ+6YNdWCX5RuC+GgmpwrDsZhtqpA2TvK/bnwn9/gd8dWqXF5zGMEmNuXSSLVL7SnwegsQ9ZjUOh2yRHsV2lYHM/1I=,iv:beZ6pDSrZt6CztU3BYI7jNr7ffdh2G9j7Iwrn5xXOJs=,tag:3rqYFGT/qYJn976sViHXJw==,type:str]
    pgp:
        - created_at: "2026-09-19T19:53:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/+OrSAW+3/m7l6u7727AtoK87QtHhMjV5AL8Ai5tD9q/o9
            Nj8tNotM+Ja4p+Gb3imjhoxSr3lT8Av7HI/fOHd18qi+vo83FFyejBtIOxG2Q4Br
            bAGGv+gJJJH7ERz8BgrlU2A8opz5Ig/tB7bTeH2x+yQ08cH2D445pdKGWaqzzZAL
            7d98GfG/6Gs+WpCeL/Ekz8YP0W/S6E7RwiIf9tswhIQk2aQYPBiJQk7eGbabq2sA
            fARDFTZIex9JZ5bPZ9jjT6glDuxR42y0pycSiw71OMq+ov9R7eF0f+GvsU5nvvkb
            TD2Cs1FTnzwhb2lmqiQZ1SKnfolBnIgamockLR17t0z9SRH3R7wCtQqyrEtJYovP
            CYluOTdh2m6Bjjf58JbjJsw9nz8AlZzXIJDesh8F5579t2pkYIK/pALFDMlfwrKA
            lBFMPLdsbDc4JtXe6n2vz1oUF2QdjQnYMtZftd1A57dLCBBu7J7K8pW39a7Uvrr2
            Jnj5tJ2wxSIGVgWDj+tWSPSdlndMIa/W0bEsJOkQUZTjcv6097UIyq6zvAN+a80Z
            nkwq/RCj/djPmjIe43g8nxGiNYImkFaXZn9+n6LvrcnPrMTaPk/PjBL26Pa8eoVt
            55QyzhAFag+LL7CX3K3nYp9z3bszMuke+XMCyC90Ajf2G+ueQ88TxOGGIm10c2DU
            aAEJAhCJHmBehTwrs2tpUYd6Rx3OmJOF2LouA2/6EhaVIBVNr/oGRCuAs9GJGzg0
            gqNEEGzSyOTLiuc0ec17i2nSnFV85PV9jABAoirJ1WbZYXLoLAoSz8JFt2yQfOqd
            XQqzKI8vPLeh
            =ZLlu
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
