apiVersion: v1
data:
    password: ENC[AES256_GCM,data:DTPREqfCXsn/20Pv,iv:nlg+Im6etD+w/ziBWc3eqxDp3qJM5O2EVEJBhd31KYg=,tag:u3fvjVSwI6YiJLuqdtEafw==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/instance: basic-memory
        app.kubernetes.io/name: basic-memory
    name: basic-memory-nas
    namespace: basic-memory
type: Opaque
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T19:53:53Z"
    mac: ENC[AES256_GCM,data:4wkOItfD6ySybQl7XCiA3Hk2HzIK4mTU95PNh6UfYSjBj+d4+5Vvj3vYUyw8x8VYBuEHTwfvK9mIzbdIBKa2Jg78BUmysRnT6wYTKSEQT6GVlTJSQ62e2WnrMqEG8pUeroaz+Jm2A6LV8ZQVylfPUfI0RBPeCr7eDV8sKYMlyUU=,iv:sRCvlPkdGqa3gY64nCP33x4+iC8V4tHMgBs3NTz3GpQ=,tag:syLghua1Q1C5FEm61Vz/Fg==,type:str]
    pgp:
        - created_at: "2026-09-19T19:53:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/9HYRdTvtnxFdJ7V7jqbKesxBYd0a+J+fwl8wbkfqg42H0
            nSDnZNvBeftE7AXRkoOQk0EYH/hSg89MgoZa50jvvcZ3rtmrxOj6zyb7xEHI4tB8
            DcuS0JdXIfwcpkqmHoX1mj5K3jUsGnMFSPvnDUKpfAEqsEbxfjeq6nG16ViPV3bw
            v8FJiIAahSZDUxmSoM54DKdnalCJWyWoIoOOVfRtWoNCgQSSSN49SdberwxzlIBe
            f1OqQmvHfXjSr5tumX1SKrnpmj9aMrqOsclRgUps7/P4QF3zCE69ap9np6A/rWKl
            PoR8GR7GGiHfiIJQju4aZf7GM0bgNOCb+vFMFGxaKrME9lS0FTEUZyLDl/a92bxU
            9Txm8x0D6k1pQxOXK6xSuptWNjNYYMven4KpxUS3gTtt5nbyGJDElzZYcyAbhBNg
            jMBmfj/TybgSvJbycAbGyhv8ePCq4MruttiQE9rnUx9yWup6cIEBMZ2Rkf/gu3VL
            tnXaQPwLbVkcAIx8HKasGmzrcwsHyCcIL3PF4Hk2JeWecXFpi2wLi2wwU8RtZ0Ay
            4x1lQZB2RQq5Lr/ddmr27CbkmeoQOT0LkxtKfC88+Y1VxpptOQmulLgCLSeYdRNw
            vONd7z+77Wnj2fhdU99gY2fr/5ZtoT05g0SycwOKUjuTrEFmVFR0CtfqLMJNfunU
            ZgEJAhDTswPyPN/rjB7CUf0HpTfcOrZDCRFP9JhDahXTY9GUtqfHtw0SCu7WLy1r
            pjI2Mw+l18QqZfJQiCPfkOWV/mnMfUlq/hxo03jICUfJdiVFo6E5cacXx2+wJnkJ
            tUKRfMt4yg==
            =z1Sl
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
