apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
      - equal:
          - namespace
        source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
      # Silence k3s embedded component alerts
      - equal: []
        source_matchers:
          - alertname = Watchdog
        target_matchers:
          - alertname = KubeControllerManagerDown
      - equal: []
        source_matchers:
          - alertname = Watchdog
        target_matchers:
          - alertname = KubeSchedulerDown
      - equal: []
        source_matchers:
          - alertname = Watchdog
        target_matchers:
          - alertname = KubeProxyDown
    receivers:
      - name: "null"
    route:
      group_by:
        - namespace
      group_interval: 5m
      group_wait: 30s
      receiver: "null"
      repeat_interval: 12h
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"
        # Silence the embedded component alerts in k3s
        - matchers:
            - alertname =~ "KubeControllerManagerDown|KubeSchedulerDown|KubeProxyDown"
          receiver: "null"
          continue: true
    templates:
      - /etc/alertmanager/config/*.tmpl
