apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-inhibit-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
data:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp:
        smarthost: smtp-relay.brevo.com:587
        from: jannegpriv@gmail.com
        auth_username: 85deaf001@smtp-brevo.com
        auth_password: ${SMTP_PASSWORD}
        require_tls: true
    
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 6h
      receiver: 'email'
      routes:
      - match:
          severity: none
        receiver: 'null'
      - match:
          severity: warning
        receiver: 'email'
      - match:
          severity: critical
        receiver: 'email'
    
    inhibit_rules:
      # Inhibit alerts for embedded K3s components
      - source_match:
          inhibit_k3s_components: 'true'
        target_match_re:
          alertname: 'KubeControllerManagerDown|KubeSchedulerDown|KubeProxyDown|etcdMembersDown|etcdInsufficientMembers|etcdNoLeader'
        equal: []
      
      # Inhibit alerts for components that have been modified for K3s
      - source_match:
          k3s_modified: 'true'
        target_match_re:
          alertname: 'etcdMembersDown|etcdInsufficientMembers|etcdNoLeader'
        equal: ['alertname']
      
      # Don't alert on NodeCPUThrottling if the node is already known to be under pressure
      - source_match:
          alertname: 'NodeHighCPULoad'
        target_match:
          alertname: 'NodeCPUThrottlingHigh'
        equal: ['instance']
      
      # Silence OpenHAB job failures during maintenance periods
      - source_match:
          alertname: 'MaintenanceMode'
          namespace: 'openhab'
        target_match_re:
          alertname: 'KubeJobFailed'
          namespace: 'openhab'
          job_name: 'openhab-backup.*'
        equal: ['namespace']
      
      # Don't alert on CPU throttling for monitoring namespace
      - source_match:
          namespace: 'monitoring'
        target_match:
          alertname: 'CPUThrottlingHigh'
          namespace: 'monitoring'
        equal: ['namespace']
    
    receivers:
    - name: 'null'
    - name: 'email'
      email_configs:
      - to: 'jannegpriv@gmail.com'
        send_resolved: true
        from: 'jannegpriv@gmail.com'
        smarthost: smtp-relay.brevo.com:587
        auth_username: 85deaf001@smtp-brevo.com
        auth_password: ${SMTP_PASSWORD}
        require_tls: true
