apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-notification-secret
  namespace: monitoring
data:
  password: dEwya3NXWHZjeE9TWUZOJQo=
  username: ODVkZWFmMDAxQHNtdHAtYnJldm8uY29tCg==
type: Opaque
