apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  configMaps:
    - alertmanager-config
  secrets:
    - alertmanager-notification-secret
  configuration:
    route:
      receiver: email
      group_by: ['alertname', 'severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - receiver: email
          matchers:
            - name: severity
              value: warning|critical
              regex: true
    receivers:
      - name: email
        email_configs:
          - to: jannegpriv@gmail.com
            from: jannegpriv@gmail.com
            smarthost: smtp-relay.brevo.com:587
            auth_username: 85deaf001@smtp-brevo.com
            auth_password:
              name: alertmanager-notification-secret
              key: password
            require_tls: true
            send_resolved: true
