apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: kube-prometheus-stack-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  configSecret: alertmanager-kube-prometheus-stack-alertmanager
  configMaps:
    - alertmanager-config
  alertmanagerConfiguration:
    name: alertmanager-config
    global:
      smtp:
        from: jannegpriv@gmail.com
        smartHost:
          host: smtp-relay.brevo.com
          port: "587"
        authUsername: 85deaf001@smtp-brevo.com
        authPassword:
          name: alertmanager-notification-secret
          key: password
        requireTLS: true
