apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: apiserver-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  groups:
    - name: ApiServer
      rules:
        - alert: ApiServerHighLatency
          expr: |
            histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job="apiserver",verb=~"LIST|WATCH"}[5m])) by (le, verb)) > 5
          for: 15m  # Increased to reduce noise
          labels:
            severity: warning
          annotations:
            summary: "API server high latency"
            description: "99th percentile of request latency is above 5 seconds for {{ $labels.verb }} requests. This may indicate k3s CPU pressure."

        - alert: ApiServerCriticalLatency
          expr: |
            histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job="apiserver",verb=~"LIST|WATCH"}[5m])) by (le, verb)) > 15
          for: 5m  # Increased to ensure it's not a temporary spike
          labels:
            severity: critical
          annotations:
            summary: "API server critical latency"
            description: "99th percentile of request latency is above 15 seconds for {{ $labels.verb }} requests. Consider restarting k3s.service."

        - alert: ApiServerHighErrorRate
          expr: sum(rate(apiserver_request_total{code=~"5.."}[5m])) / sum(rate(apiserver_request_total[5m])) * 100 > 3
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High API server error rate"
            description: "Error rate is above 3% ({{ $value }}%)"

        - alert: ApiServerCriticalErrorRate
          expr: sum(rate(apiserver_request_total{code=~"5.."}[5m])) / sum(rate(apiserver_request_total[5m])) * 100 > 10
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Critical API server error rate"
            description: "Error rate is above 10% ({{ $value }}%). Consider restarting k3s.service."

        - alert: ApiServerHighMemory
          expr: process_resident_memory_bytes{job="apiserver"} > 1.5 * 1024 * 1024 * 1024
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "API server high memory usage"
            description: "API server is using more than 1.5GB of memory for over 15 minutes."
