apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ceph-prometheus-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
spec:
  groups:
  - name: ceph.rules
    rules:
    - alert: CephOSDNearFull
      expr: ceph_osd_utilization > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Ceph OSD Near Full"
        description: "Ceph OSD {{ $labels.ceph_daemon }} on {{ $labels.instance }} is at {{ $value }}% capacity (above 85%). Consider rebalancing data or adding more storage."
        runbook_url: "https://github.com/jannegpriv/k3s-cluster-config/blob/main/COMPREHENSIVE_README.md#troubleshooting-common-issues"
    
    - alert: CephOSDCriticallyFull
      expr: ceph_osd_utilization > 95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Ceph OSD Critically Full"
        description: "Ceph OSD {{ $labels.ceph_daemon }} on {{ $labels.instance }} is at {{ $value }}% capacity (above 95%). Immediate action required!"
        runbook_url: "https://github.com/jannegpriv/k3s-cluster-config/blob/main/COMPREHENSIVE_README.md#troubleshooting-common-issues"
    
    - alert: CephPoolNearFull
      expr: ceph_pool_percent_used > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Ceph Pool Near Full"
        description: "Ceph Pool {{ $labels.pool_id }} ({{ $labels.name }}) is at {{ $value | humanizePercentage }} capacity (above 85%). Consider reducing replication factor or adding more storage."
        runbook_url: "https://github.com/jannegpriv/k3s-cluster-config/blob/main/COMPREHENSIVE_README.md#troubleshooting-common-issues"
    
    - alert: CephClusterNearFull
      expr: ceph_cluster_total_used_bytes / ceph_cluster_total_bytes > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Ceph Cluster Near Full"
        description: "Ceph cluster is at {{ $value | humanizePercentage }} capacity (above 85%). Consider adding more storage or cleaning up unused data."
        runbook_url: "https://github.com/jannegpriv/k3s-cluster-config/blob/main/COMPREHENSIVE_README.md#troubleshooting-common-issues"
    
    - alert: CephOSDDown
      expr: ceph_osd_up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Ceph OSD Down"
        description: "Ceph OSD {{ $labels.ceph_daemon }} on {{ $labels.instance }} is down."
        runbook_url: "https://github.com/jannegpriv/k3s-cluster-config/blob/main/COMPREHENSIVE_README.md#troubleshooting-common-issues"
