apiVersion: v1
kind: Secret
metadata:
    name: deadmans-switch
    namespace: monitoring
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:qayNS4soApyLKITvXyJfqojv4rjDbJUlck0bwX/j9qHt1jjpNju6PhCtlCzMO/8ctfrJg6QZLUY=,iv:FGYdy77wGVsxOHTixXvOYYnNbbCVbvWL0E/HgDPseZA=,tag:45SpumIGFPFgInHc9bs4cw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T14:42:55Z"
    mac: ENC[AES256_GCM,data:EsT6rP8h8lQ20C/4IZGdn35tKRAi7SjPJsazR3f10oEngkBFpujosaQxWC50G3WxTCPX+IszTXrt1+mvrCa4TR20N5E/3X8PA9eQ8xmSVazgGQIQfhfNXQ/wbEUYKbbQ0t5MP5hlhJU2aB/0kcip85mt7JVkDKmidwgd+14NKUk=,iv:mK4Vun6muHGKFA70d+2iJ3puoHJej21QCdoQHdliuXc=,tag:WAiXKjq79VgatVyQOHGmIw==,type:str]
    pgp:
        - created_at: "2026-07-23T14:42:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/+PbjBzQgphTTrTXxAcDLvbVyEcbuP4ov/dDVhr0EDxAvJ
            nBqyeUr7kUydTuKuC8ROQ9Pst9L34bMe+rpCEdL5fC+0Fhv7DX/HDWxK4tP39E90
            MdFa/HvGbEOlVufgkZwRDWKzDTwY4LybWZiWjyPdcIubMgT0mfgOethDujnwscbG
            9EZ+YmB8F5msKfZTbesJGs+O19/C736WPAI86y74n4xXtmqVYV2mDAsImem+ayKP
            X+hZ5iD6NUR+Fv51MZAflqkhus0fqaM5J7YchlQn343lTAXxBZtbtJdegfDBba+h
            fSCtB0JgaLrIupK9r41m1oAuvWWplqY6tR3qAMraAV68jJQJSlQykHlD0b9dCkjx
            w5NeUp/UNqeiWMKToYR1kgcDA++pTAK0utOhhXKYbyDXw6zBFLVqP46/JO/O0zsI
            FWfFl1CVvRFM0Z+mst23OqXAGksMZxlkYPajk6TQkyniRyBSLRlCiHxwRFXfebe1
            kb43hv4f5FHYoYDuOTb0hw07OTZb9wNIxrAoVS9Uwp3klKQ5FC8M6VHgaMNtpeUz
            tu/ARVDk+VNUpXxPGgAZ4XxWZzsauJpd7mbCYO0JFTnqGB76EkSgv3XYSZUZXD7I
            zCd3CsabFVUP8MfiYPx+YHQNtgaq8DN7sB6d2I5QsG2UYOun71R3Bg1tNDztY2PU
            ZgEJAhCRPToBXCRbZlbYvwnJPC3TyGZZofy7/0UbXUFSUqSONsDmW18OjvT7OLnn
            KfziUYx3gliNUYv8ufgb/xurdb4KWe3oAfAjIrcfHLVh3S01uth5QNZG7V5bxYbw
            8njnBglKpg==
            =IRw1
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
