apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.5.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.local
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.local
    alertmanager:
      alertmanagerSpec:
        configMaps:
          - alertmanager-config
        secrets:
          - alertmanager-notification-secret
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - alertmanager.local
