apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.5.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.local
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: monitoring
      persistence:
        enabled: true
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m  # Increased from 100m
          memory: 256Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: NotIn
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
    
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.local
      prometheusSpec:
        # Resource limits
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 800m  # Increased from 500m
            memory: 1Gi
        # Persistent storage configuration
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        # Performance optimizations
        retention: 15d  # Increased from 3d since we now have persistent storage
        retentionSize: "15GB"  # Increased from 8GB
        scrapeInterval: "90s"  # Increased from 60s to reduce scrape frequency
        evaluationInterval: "90s"  # Increased from 60s to reduce evaluation frequency
        enableAdminAPI: false  # Disable admin API to reduce attack surface
        walCompression: true  # Enable WAL compression to reduce disk I/O
        # Node affinity to keep off master node
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                  - "true"
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                  - "true"
    
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.local
        secrets:
          - alertmanager-notification-secret
        # Persistent storage configuration
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m  # Increased from 50m
            memory: 128Mi
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                  - "true"
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                  - "true"
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - alertmanager.local
    
    prometheusOperator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
    
    kube-state-metrics:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    
    nodeExporter:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
