apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.5.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.local
      # Add this config section for timezone settings
      grafana.ini:
        default:
          default_timezone: "Europe/Stockholm"    
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: monitoring
      persistence:
        enabled: true
        storageClassName: rook-ceph-block
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      resources:
        requests:
          cpu: 300m
          memory: 128Mi
        limits:
          cpu: 800m  # Increased from 600m to reduce CPU throttling
          memory: 256Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-w-3
    
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.local
      prometheusSpec:
        # Resource limits
        resources:
          requests:
            cpu: 400m
            memory: 768Mi
          limits:
            cpu: 2000m  # Increased from 1500m to reduce CPU throttling
            memory: 2Gi  # Increased from 1Gi to prevent OOMKilled
        # Persistent storage configuration
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        # Performance optimizations
        retention: 15d  # Increased from 3d since we now have persistent storage
        retentionSize: "15GB"  # Increased from 8GB
        scrapeInterval: "90s"  # Increased from 60s to reduce scrape frequency
        evaluationInterval: "90s"  # Increased from 60s to reduce evaluation frequency
        enableAdminAPI: false  # Disable admin API to reduce attack surface
        walCompression: true  # Enable WAL compression to reduce disk I/O
        # Node affinity to keep off master node
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                  - "true"
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                  - "true"
    
    alertmanager:
      alertmanagerSpec:
        externalUrl: http://alertmanager.local
        secrets:
          - alertmanager-notification-secret
        # Persistent storage configuration
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m  # Increased from 50m
            memory: 128Mi
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: NotIn
                  values:
                  - "true"
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                  - "true"
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - alertmanager.local
    
    prometheusOperator:
     enabled: true
      replicas: 1 
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 500m  # Increased from 300m to reduce CPU throttling
          memory: 256Mi
    
    kube-state-metrics:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 300m  # Increased from 200m to reduce CPU throttling
          memory: 128Mi
    
    nodeExporter:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
          
    # K3s component monitoring configuration
    kubeControllerManager:
      endpoints:
        - 192.168.50.75  # Your k3s-m-1 IP
      service:
        port: 10257
        targetPort: 10257
      serviceMonitor:
        https: true
        insecureSkipVerify: true

    kubeScheduler:
      endpoints:
        - 192.168.50.75  # Your k3s-m-1 IP
      service:
        port: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true

    kubeProxy:
      service:
        port: 10249
        targetPort: 10249
        selector:
          k8s-app: pushprox-kube-proxy-client
      serviceMonitor:
        proxyUrl: http://pushprox-kube-proxy-proxy.kube-system.svc:8080
        https: false
        relabelings:
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_ip
            targetLabel: pod_ip
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: instance
