apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.5.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.local
    prometheus:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - prometheus.local
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
          smtp_from: jannegpriv@gmail.com
          smtp_smarthost: smtp-relay.brevo.com:587
          smtp_auth_username: 85deaf001@smtp-brevo.com
          smtp_auth_password:
            secret:
              name: alertmanager-notification-secret
              key: password
          smtp_require_tls: true
        route:
          group_by: ['alertname', 'severity']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          receiver: email
          routes:
            - receiver: email
              matchers:
                - name: severity
                  value: warning|critical
                  regex: true
        receivers:
          - name: email
            email_configs:
              - to: jannegpriv@gmail.com
                send_resolved: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - alertmanager.local
