apiVersion: v1
kind: Service
metadata:
  name: k3s-kubelet-metrics
  namespace: kube-system
  labels:
    k8s-app: k3s-kubelet
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
    targetPort: 10250
  selector: {}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k3s-kubelet-metrics
  namespace: kube-system
  labels:
    k8s-app: k3s-kubelet
subsets:
- addresses:
  - ip: 192.168.50.75
    nodeName: k3s-m-1
    targetRef:
      kind: Node
      name: k3s-m-1
  ports:
  - name: https-metrics
    port: 10250
    protocol: TCP
