apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-kubelet
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    honorLabels: true
    relabelings:
    - action: replace
      targetLabel: job
      replacement: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: k3s-kubelet
