apiVersion: v1
kind: Endpoints
metadata:
  name: k3s-metrics
  namespace: kube-system
  labels:
    app: k3s
subsets:
  - addresses:
      - ip: 192.168.50.75  # Your control plane node IP
    ports:
      - name: https
        port: 10250
        protocol: TCP
