apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k3s-alert-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: K3sAlerts
      rules:
        # Disable false positives for k3s
        - alert: KubeControllerManagerDown
          expr: absent(up{job="kube-controller-manager"} == 1)
          for: 5m
          labels:
            severity: none  # Changed from critical
          annotations:
            description: "This alert is disabled for k3s as the controller manager is embedded"
            summary: "Disabled - KubeControllerManager monitoring"

        - alert: KubeSchedulerDown
          expr: absent(up{job="kube-scheduler"} == 1)
          for: 5m
          labels:
            severity: none  # Changed from critical
          annotations:
            description: "This alert is disabled for k3s as the scheduler is embedded"
            summary: "Disabled - KubeScheduler monitoring"

        - alert: KubeProxyDown
          expr: absent(up{job="kube-proxy"} == 1)
          for: 5m
          labels:
            severity: none  # Changed from critical
          annotations:
            description: "This alert is disabled for k3s as kube-proxy is managed differently"
            summary: "Disabled - KubeProxy monitoring"
