apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-resource-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: NodeResources
      rules:
        - alert: NodeHighCPUUsage
          expr: instance:node_cpu_utilisation:rate5m * 100 > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on node"
            description: "Node {{ $labels.instance }} CPU usage is above 80% for more than 5 minutes. Consider investigating running pods or restarting k3s if persistent."

        - alert: NodeCPUThrottling
          expr: sum(increase(container_cpu_cfs_throttled_periods_total[5m])) by (container, pod, namespace) > 10
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Container CPU throttling detected"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} ({{ $labels.namespace }}) is being throttled significantly. This may indicate resource constraints."

        - alert: K3sCPUPressure
          expr: rate(process_cpu_seconds_total{job="kubelet"}[5m]) * 100 > 50
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High k3s CPU usage"
            description: "k3s process is using more than 50% CPU over 5 minutes. This may lead to cluster instability."

        - alert: K3sCriticalCPUPressure
          expr: rate(process_cpu_seconds_total{job="kubelet"}[5m]) * 100 > 80
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Critical k3s CPU usage"
            description: "k3s process is using more than 80% CPU over 2 minutes. Consider restarting k3s.service if persistent."

        - alert: NodeHighMemoryUsage
          expr: instance:node_memory_utilisation:ratio * 100 > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on node"
            description: "Node {{ $labels.instance }} memory usage is above 85% for more than 5 minutes"

        - alert: NodeSwapUsage
          expr: instance:node_memory_swap_io_bytes:rate5m > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Swap usage detected"
            description: "Node {{ $labels.instance }} is using swap memory. This may indicate memory pressure."

        - alert: NodeHighDiskUsage
          expr: max((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"}) by (instance) > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High disk usage on node"
            description: "Node {{ $labels.instance }} disk usage is above 85%"

        - alert: NodeCriticalCPUUsage
          expr: instance:node_cpu_utilisation:rate5m * 100 > 90
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Critical CPU usage on node"
            description: "Node {{ $labels.instance }} CPU usage is above 90% for more than 2 minutes"

        - alert: NodeCriticalMemoryUsage
          expr: instance:node_memory_utilisation:ratio * 100 > 95
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Critical memory usage on node"
            description: "Node {{ $labels.instance }} memory usage is above 95% for more than 2 minutes"
