apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-resource-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: NodeResources
      rules:
        - alert: NodeHighCPUUsage
          expr: instance:node_cpu_utilisation:rate5m * 100 > 5
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on node"
            description: "Node {{ $labels.instance }} CPU usage is above 80% for more than 10 minutes"

        - alert: NodeCPUThrottling
          expr: sum(increase(container_cpu_cfs_throttled_periods_total[5m])) by (container, pod, namespace) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Container CPU throttling detected"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} ({{ $labels.namespace }}) is being throttled"

        - alert: NodeHighMemoryUsage
          expr: instance:node_memory_utilisation:ratio * 100 > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on node"
            description: "Node {{ $labels.instance }} memory usage is above 85% for more than 5 minutes"

        - alert: NodeSwapUsage
          expr: instance:node_memory_swap_io_bytes:rate5m > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Swap usage detected"
            description: "Node {{ $labels.instance }} is using swap memory"

        - alert: NodeHighDiskUsage
          expr: max((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) * 100 / node_filesystem_size_bytes{mountpoint="/"}) by (instance) > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High disk usage on node"
            description: "Node {{ $labels.instance }} disk usage is above 85%"

        - alert: NodeCriticalCPUUsage
          expr: instance:node_cpu_utilisation:rate5m * 100 > 97
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Critical CPU usage on node"
            description: "Node {{ $labels.instance }} CPU usage is above 95% for more than 5 minutes"

        - alert: NodeCriticalMemoryUsage
          expr: instance:node_memory_utilisation:ratio * 100 > 97
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Critical memory usage on node"
            description: "Node {{ $labels.instance }} memory usage is above 97% for more than 5 minutes"

        - alert: OpenHABHighResourceUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="openhab"}[5m])) * 100 > 150 or sum(container_memory_working_set_bytes{namespace="openhab"}) > 2.5 * 1024 * 1024 * 1024
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "OpenHAB high resource usage"
            description: "OpenHAB is using high resources (either >150% CPU or >2.5GB memory) for more than 10 minutes"
