apiVersion: v1
kind: Secret
metadata:
    name: basic-memory-chatgpt-tunnel
    namespace: basic-memory
type: Opaque
stringData:
    tunnel-id: ENC[AES256_GCM,data:SuGQ4/SnP5G3w+4NM9zgwPBqrQOS7R3E2FGccRVDZEUO7czsh6Gj,iv:VHy080gpRnq9DDAgF8xBcXsCXoayCEe/7e7I5XRJKEE=,tag:uy/u5bReTQQl0bUx7mogLA==,type:str]
    api-key: ENC[AES256_GCM,data:oUi8OKN91uDQVQIcz9bVmXmFuDADfqcisAArZFNE4wQym+0fl3HIwT1uDT0advFj4GJehifC9vpjxRpeM9az6Xd8avnarfcu8xbZW+huqXA1s81BB8q1lXRsM0yxXCdrTQbOWtA+dmM3PvtOn/V1ZE9Cl2eAc/f2FyFctKA2ADINa8wQhij4zDbucQIx4IkOoVIanm7TZg23HdT9mm3ADGZrCBI=,iv:C9XIR53IwILYuJ0NpwRjDsWqzXOA5tVC0mNzGIUxThY=,tag:SwG2bP4syI+V9mt5i8VDQQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T12:24:32Z"
    mac: ENC[AES256_GCM,data:irsQ3RqTThCOiqwpcl0aUcXh1KpBDPczCKWnpYLIligjDdwMBaEGL7PdhDwuVpV72VCz7rYhfSpR//CxbeQzvcUrWjJtljH2KzHMDZmvEsnTzvhdDg6BOUxqeSx814iyrOv5Fcd3+Tkv9UEtql+VR4NdzMy2IT4tWiJ4IdS5i2E=,iv:NOTdslvLDJShubTNj61LSmI/2nP5XmQ3MiZCxkuA3fM=,tag:luRcRqBlpXSeEqJUyv9wKQ==,type:str]
    pgp:
        - created_at: "2026-09-27T12:24:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ//bAB8GQ94fsb7q/OKpwToyLVKwai/5c7tl7JTN1VQYZeb
            1nCIrZSC9XsHPoWjlEdlo58SG9yVLQc0cETtv+6wvM/KgnLGwi9Xa3OmjlAyAgSO
            7PqaWevIi8OkGvTz6UQkazuKw2jHJ4JiUTRA9qbVcianoGNEoaAZW3rO+rh2PIau
            AzswB6SnoxLA3k2ZdJE1YzL62MwVdqkSlblOOglIcs2JbhAXQNqCmnUTDby8Rdjq
            HsI0+o1Tuw/OKLVb9KlPt+42BFC7N4LcHvbbWgrJ/YTVYqQqUW9kmy0q53xO5PEz
            9xp2YuzRzLEtn4fj58zu879NjDANnWn9HaYXrnpkDMLHxth+IIH2NYCljVTMEoLO
            RkQxvsTVwIpodaThGgE1e7jP7A1/SvXOD2NJ0L1vikNayxhQbA+FACTI+0XTpozu
            ttj0Vun1Dnq1rXLxkcW6EshRLnEpliW/G177hJcSsJXCLHNrBY/h/KlkFIw4SNec
            skqz15IskUswCtzWwqqRY1m0YX0935rqJuYLc+ZCnDUKFotG+WII2oWAX2m2TUOt
            IeH9FjFR7WJ/PN267UY2nBEOS1Z1hQDsAHax5IUo47FgxX2c48yuXedohqDO/A/U
            Sbq8djePj9/31wB5HazZwL7k+fdNH06aDpwvjc3+yF1fv2GopiamPOOyhrmkFODU
            ZgEJAhCiVdKWA6sHAoDaWb19aOz7i7GBsm7bQhca2F42AD7Uya2nFM4i0K79I+NX
            duoyhJA/FemsCg1PjLnuaDs0rWfKgcABM9Z+Sy6IYehhxqHVmGST1kvweOoyt/aC
            930K7el0ig==
            =bOoF
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
