apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: basic-memory
resources:
- deployment.yaml
- network-policy.yaml
- credentials.secret.sops.yaml
configMapGenerator:
- name: basic-memory-chatgpt-tunnel
  files:
  - config.yaml
