apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-postgres-pvc
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-postgres
  namespace: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost-postgres
  template:
    metadata:
      labels:
        app: mattermost-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: mattermost
        - name: POSTGRES_USER
          value: mattermost
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-secrets
              key: postgres-password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mattermost-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-postgres
  namespace: mattermost
spec:
  selector:
    app: mattermost-postgres
  ports:
  - port: 5432
    targetPort: 5432
