apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-data
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
