apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
type: Opaque
# The actual secret data is managed outside of Git
# Created manually with: kubectl create secret generic ghcr-auth -n flux-system --from-literal=username=jannegpriv --from-literal=password=your_token
