apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
type: Opaque
stringData:
  username: jannegpriv
  password: YOUR_GITHUB_PAT  # Replace with your actual GitHub Personal Access Token
