  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: cloudflared
    namespace: cloudflare
  spec:
    selector:
      matchLabels:
        app: cloudflared
    replicas: 1
    template:
      metadata:
        labels:
          app: cloudflared
      spec:
        containers:
          - name: cloudflared
            image: cloudflare/cloudflared:latest
            args:
              - tunnel
              - --config
              - /etc/cloudflared/config.yaml
              - run
            volumeMounts:
              - name: config
                mountPath: /etc/cloudflared/config.yaml
                subPath: config.yaml
              - name: creds
                mountPath: /etc/cloudflared/credentials.json
                subPath: credentials.json
        volumes:
          - name: config
            configMap:
              name: cloudflared-config-cg42tbdgk5
          - name: creds
            secret:
              secretName: tunnel-credentials