apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare

resources:
  - cloudflare-deployment.yaml

configMapGenerator:
  - name: cloudflared-config
    files:
      - config.yaml=cloudflare-config.yaml
