apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeshark
  namespace: kubeshark
spec:
  secretName: kubeshark-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - kubeshark.local
