apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeshark
  namespace: kubeshark
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeshark
      version: '52.4'  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: kubeshark
        namespace: flux-system
      interval: 1m
  values:
    # Resource limits to protect your cluster
    resources:
      hub:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      worker:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
    
    # Enable Prometheus metrics
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    
    # Configure persistent storage for captures
    persistence:
      enabled: true
      storageClass: "local-path"  # Using k3s default storage class
      size: 1Gi

    # Web interface configuration
    ingress:
      enabled: true
      className: traefik
      host: kubeshark.local
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
      paths:
        - path: /
          pathType: Prefix
    
    # Node affinity to avoid running intensive components on master
    worker:
      nodeSelector:
        node-role.kubernetes.io/master: "false"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
