apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeshark
  namespace: kubeshark
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeshark
      version: '52.4'  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: kubeshark
        namespace: flux-system
      interval: 1m
  values:
    # Resource limits to protect your cluster
    resources:
      hub:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "50m"
          memory: "64Mi"
      worker:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"
    
    # Enable Prometheus metrics
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
      packetCapture:
        enabled: true
      storage:
        enabled: true

    service:
      front:
        port: 8899

    tap:
      proxy:
        front:
          port: 8899
    
    # Configure persistent storage for captures
    persistence:
      enabled: true
      storageClass: "local-path"  # Using k3s default storage class
      size: 1Gi

    # Web interface configuration
    ingress:
      enabled: false
    
    # Node affinity to avoid running intensive components on master
    worker:
      nodeSelector:
        node-role.kubernetes.io/master: "false"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
