apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kubeshark
  namespace: kubeshark
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`kubeshark.local`)
    services:
    - name: kubeshark-front
      port: 80
