apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeshark
  namespace: kubeshark
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubeshark
  namespaceSelector:
    matchNames:
      - kubeshark
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
    - port: worker-metrics
      path: /metrics
      interval: 30s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
