apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - port: 1883
      protocol: TCP
      targetPort: 1883
      name: mosquitto
  externalIPs:
    - 192.168.50.75
