apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    name: mosquitto
spec:
  serviceName: mosquitto
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      serviceAccountName: default
      containers:
      - name: mosquitto-broker
        image: eclipse-mosquitto:latest
        ports:
         - containerPort: 1883
        resources:
         limits:
           cpu: 300m
           memory: 1Gi
         requests:
           cpu: 50m
           memory: 256Mi
        volumeMounts:
         - name: mosquitto-config
           mountPath: /mosquitto/config
           readOnly: false
         - name: mosquitto-data
           mountPath: /mosquitto/data
           readOnly: false
         - name: mosquitto-log
           mountPath: /mosquitto/log
           readOnly: false
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        persistentVolumeClaim:
            claimName: mosquitto-data-claim
      - name: mosquitto-log
        persistentVolumeClaim:
            claimName: mosquitto-log-claim
