kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mosquitto
  name: mosquitto-conf-claim
  namespace: mosquitto
  storageClassName: rook-ceph-block
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mosquitto
  name: mosquitto-log-claim
  namespace: mosquitto
  storageClassName: rook-ceph-block
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mosquitto 
  name: mosquitto-data-claim
  namespace: mosquitto
  storageClassName: rook-ceph-block
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
