apiVersion: v1
kind: ServiceAccount
metadata:
  name: openhab-backup
  namespace: openhab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openhab-backup
  namespace: openhab
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openhab-backup
  namespace: openhab
subjects:
- kind: ServiceAccount
  name: openhab-backup
  namespace: openhab
roleRef:
  kind: Role
  name: openhab-backup
  apiGroup: rbac.authorization.k8s.io
