apiVersion: batch/v1
kind: CronJob
metadata:
  name: openhab-backup
  namespace: openhab
spec:
  schedule: "0 2 * * *"  # Run at 2 AM every day
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: openhab-backup
          containers:
          - name: backup
            image: debian:bullseye-slim
            command: ["/bin/bash", "-c"]
            args:
              - |
                apt-get update && \
                apt-get install -y sshpass curl apt-transport-https && \
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
                chmod +x kubectl && mv kubectl /usr/local/bin/ && \
                /scripts/backup-script.sh
            env:
              - name: NAS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nas-credentials
                    key: password
            volumeMounts:
            - name: backup-script
              mountPath: /scripts
          volumes:
          - name: backup-script
            configMap:
              name: openhab-backup-script
              defaultMode: 0755
          restartPolicy: OnFailure
