apiVersion: batch/v1
kind: CronJob
metadata:
  name: openhab-backup
  namespace: openhab
spec:
  schedule: "0 2 * * *"  # Run at 2 AM every day
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: openhab-backup
          containers:
          - name: backup
            image: bitnami/kubectl:latest
            command: ["/bin/bash"]
            args: ["/scripts/backup-script.sh"]
            env:
              - name: NAS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nas-credentials
                    key: password
            volumeMounts:
            - name: backup-script
              mountPath: /scripts
          volumes:
          - name: backup-script
            configMap:
              name: openhab-backup-script
              defaultMode: 0755
          restartPolicy: OnFailure
