apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openhab
resources:
  - namespace.yaml
  - openhab-claims.yaml
  - openhab-service.yaml
  - openhab-statefulset.yaml
  - openhab-traefik.yaml
  - openhab-middleware.yaml
