apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openhab-production-https
  namespace: openhab
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`openhab.k3s.nu`)
      middlewares:
        - name: openhab-https
          namespace: openhab
      services:
        - name: openhab-production
          port: 8443
  tls:
    secretName: openhab-k3s-nu-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openhab-production-http
  namespace: openhab
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`openhab.k3s.nu`)
      services:
        - name: openhab-production
          port: 8080