apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openhab-https
  namespace: openhab
spec:
  headers:
    sslRedirect: true
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    customRequestHeaders:
      X-Forwarded-Proto: "https"
