kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: openhab-production
  name: openhab-production-conf-claim
  namespace: openhab
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: openhab-production
  name: openhab-production-userdata-claim
  namespace: openhab
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: openhab-production
  name: openhab-production-addons-claim
  namespace: openhab
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: openhab-production
  name: openhab-production-karaf-claim
  namespace: openhab
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

