apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  # Ceph version configuration
  ROOK_CSI_CEPH_IMAGE: "quay.io/ceph/ceph:v18.2.2"
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"
  
  # CSI driver configuration
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_CSI_ENABLE_RBD: "true"
  ROOK_CSI_REGISTRAR_IMAGE: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0"
  ROOK_CSI_PROVISIONER_IMAGE: "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2"
  ROOK_CSI_ATTACHER_IMAGE: "registry.k8s.io/sig-storage/csi-attacher:v4.3.0"
  ROOK_CSI_RESIZER_IMAGE: "registry.k8s.io/sig-storage/csi-resizer:v1.8.0"
  ROOK_CSI_CEPHCSI_IMAGE: "quay.io/cephcsi/cephcsi:v3.11.0"
  
  # Host path configuration
  ROOK_DATA_DIR_HOST_PATH: "/var/lib/rook"
  
  # Path override configuration
  ROOK_HOST_PATH_OVERRIDE: "true"
  ROOK_MON_PATH_PREFIX_OVERRIDE: "/var/lib/rook"
  ROOK_LOG_DIR_PATH: "/var/lib/rook/log"
  ROOK_CRASH_COLLECTOR_DIR_PATH: "/var/lib/rook/crash"
  
  # Skip version check to avoid reconciliation
  ROOK_SKIP_CEPH_VERSION_CHECK: "true"
  # Skip CSI version check to avoid issues with ARM64 architecture
  ROOK_CSI_SKIP_VERSION_CHECK: "true"
  
  # Disable CSI version job reporter to prevent the cephcsi executable not found error
  CSI_ENABLE_CEPHCSI_VERSION_JOB_REPORTER: "false"
  
  # Allow monitors to run on the same node
  CSI_FORCE_CEPHFS_KERNEL_CLIENT: "true"
  CSI_VOLUME_MOUNT_ROOTPATH: "/var/lib/kubelet/pods"
  ROOK_ENABLE_DISCOVERY_DAEMON: "false"
  
  # Additional monitor configuration
  ROOK_MON_OUT_TIMEOUT: "600"
  ROOK_MON_HEALTHCHECK_INTERVAL: "45s"
  ROOK_MON_HEALTHCHECK_TIMEOUT: "30s"
  
  # Disable crash collector
  ROOK_DISABLE_DEVICE_HOTPLUG: "true"
  ROOK_ENABLE_FSGROUP_VOLUME_DIR: "false"
