apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-ceph-log
  namespace: rook-ceph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
