apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  # Ceph version configuration
  ROOK_CSI_CEPH_IMAGE: "quay.io/ceph/ceph:v18.2.2"
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"
  
  # CSI driver configuration
  ROOK_CSI_ENABLE_CEPHFS: "true"
  ROOK_CSI_ENABLE_RBD: "true"
  
  # Host path configuration
  ROOK_DATA_DIR_HOST_PATH: "/var/lib/rook"
  
  # Skip version check to avoid reconciliation
  ROOK_SKIP_CEPH_VERSION_CHECK: "true"
