apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
  continueUpgradeAfterChecksEvenIfNotHealthy: true
  crashCollector:
    disable: true
  dashboard:
    enabled: true
    ssl: false
  dataDirHostPath: /var/lib/rook
  mgr:
    modules:
    - enabled: true
      name: prometheus
  mon:
    allowMultiplePerNode: false
    count: 3
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
  skipUpgradeChecks: true
  storage:
    useAllDevices: true
    useAllNodes: true
  placement:
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - k3s-m-1
    mon:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - rook-ceph-mon
          topologyKey: kubernetes.io/hostname
  resources:
    mgr:
      limits:
        cpu: "3.0"
        memory: "1Gi"
      requests:
        cpu: "0.8"
        memory: "500Mi"
    mon:
      limits:
        cpu: "1.5"
        memory: "500Mi"
      requests:
        cpu: "0.3"
        memory: "250Mi"
    osd:
      limits:
        cpu: "3"
        memory: "4Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
    # healthChecks
  # Valid values for daemons are 'mon', 'osd', 'status'
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    # Change pod liveness probe timing or threshold values. Works for all mon,mgr,osd daemons.
    livenessProbe:
      mon:
        probe:
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
      mgr:
        probe:
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
      osd:
        probe:
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
