apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  # Specify the Ceph version
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  # Configure a single monitor
  mon:
    count: 1
    allowMultiplePerNode: true
  # Skip version check
  skipUpgradeChecks: true
  # Disable monitoring
  monitoring:
    enabled: false
  # Disable crash collector
  crashCollector:
    disable: true
