apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-mon-storage
provisioner: rancher.io/local-path
parameters:
  path: /var/lib/rook/mon
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
