apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  # Specify the Ceph version
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  # Use existing monitors
  mon:
    count: 1
    allowMultiplePerNode: true
