apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 2
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: false
    modules:
    - name: dashboard
      enabled: true
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  # Add CSI configuration to match what's in the cluster
  csi:
    cephfs: {}
    readAffinity:
      enabled: true
  # cluster level storage configuration and selection
  storage:
    useAllNodes: true
    useAllDevices: true
