apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  # Specify the Ceph version
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  # Configure monitors
  mon:
    count: 2
    allowMultiplePerNode: true
  # Skip version check
  skipUpgradeChecks: true
  # Disable monitoring
  monitoring:
    enabled: false
  # Disable crash collector
  crashCollector:
    disable: true
  # Configure mgr modules
  mgr:
    modules:
    - name: dashboard
      enabled: true
    - name: nfs
      enabled: false
  # Configure the Ceph CSI drivers
  csi:
    # Enable the CSI drivers
    enabled: true
    # Enable RBD driver
    enableRbdDriver: true
    # Enable CephFS driver
    enableCephfsDriver: true
    # Configure provisioner
    provisionerTolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    # Configure plugin
    pluginTolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    # Configure read affinity
    readAffinity:
      enabled: true
    # CSI driver settings
    cephfs:
      enabled: true
    rbd:
      enabled: true
