apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v18.2.2
  cleanupPolicy:
    sanitizeDisks: {}
  crashCollector:
    disable: true
  csi:
    cephfs: {}
    readAffinity:
      enabled: true
  dashboard:
    enabled: true
    port: 8443
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement: {}
  external: {}
  healthCheck:
    daemonHealth:
      mon: {}
      osd: {}
      status: {}
  logCollector: null
  mgr:
    modules:
    - enabled: true
      name: dashboard
    - enabled: false
      name: nfs
  mon:
    allowMultiplePerNode: true
    count: 2
  monitoring:
    enabled: false
  network:
    multiClusterService: {}
  security:
    keyRotation:
      enabled: false
    kms: {}
  skipUpgradeChecks: true
  storage:
    flappingRestartIntervalHours: 0
    useAllNodes: true
    useAllDevices: true
