apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-csi-detect-version
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
      - name: cmd-reporter
        image: quay.io/cephcsi/cephcsi:v3.11.0
        command: ["/cephcsi"]
        args: ["--version"]
