apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - dashboard-password-secret.yaml
  - toolbox.yaml
  - ceph-ingressroute.yaml
  - ceph-version-configmap.yaml
  - hostpath-fix-configmap.yaml
  - ceph-log-pvc.yaml
  - ceph-mon-storageclass.yaml
  - create-mon-dirs-job.yaml
  - operator.yaml
  - csi-versions-configmap.yaml
  - csi-version-job.yaml
  # Removed cluster.yaml to avoid conflicts with existing CephCluster resource

patchesStrategicMerge:
  - operator-patch.yaml
  # Removed csi-version-job-patch.yaml as we now have a dedicated resource file
