apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - ceph-ingressroute.yaml
  - ceph-version-configmap.yaml
  - hostpath-fix-configmap.yaml
  - ceph-log-pvc.yaml

patchesStrategicMerge:
  - cephcluster-patch.yaml
