apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - ceph-ingressroute.yaml
  - ceph-version-configmap.yaml

patchesStrategicMerge:
  - cephcluster-patch.yaml
