apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - dashboard-password-secret.yaml
  - toolbox.yaml
  - ceph-ingressroute.yaml
  - operator-config.yaml
  - ceph-cluster.yaml
  - ceph-dashboard-service.yaml
  - ceph-ingress.yaml
