apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard.yaml
  - dashboard-password-job.yaml
  - dashboard-password-rbac.yaml
  - ceph-ingressroute.yaml
  - ceph-version-configmap.yaml
  - hostpath-fix-configmap.yaml
  - ceph-log-pvc.yaml
  - ceph-mon-storageclass.yaml
  - create-mon-dirs-job.yaml

patchesStrategicMerge:
  - cephcluster-patch.yaml
