apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
      - name: rook-ceph-operator
        envFrom:
        - configMapRef:
            name: rook-ceph-operator-config
        env:
        - name: ROOK_CSI_ENABLE_RBD
          value: "true"
        - name: ROOK_CSI_ENABLE_CEPHFS  
          value: "true"
        - name: ROOK_CSI_SKIP_VERSION_CHECK
          value: "false"
        - name: CSI_ENABLE_CEPHCSI_VERSION_JOB_REPORTER
          value: "true"
        - name: CSI_DISABLE_VERSION_JOB
          value: "false"
        - name: ROOK_CSI_DISABLE_VERSION_JOB
          value: "false"
        - name: ROOK_DISABLE_DISCOVERY_DAEMON
          value: "false"
        - name: ROOK_CSI_CEPHCSI_IMAGE
          value: "quay.io/cephcsi/cephcsi:v3.11.0"
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0"
        - name: ROOK_CSI_RESIZER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-resizer:v1.13.1"
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-provisioner:v5.1.0"
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0"
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-attacher:v4.8.0"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOK_HOST_PATH_OVERRIDE
          value: "true"
        - name: ROOK_MON_PATH_PREFIX_OVERRIDE
          value: /var/lib/rook
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: rook-data
          mountPath: /var/lib/rook
      volumes:
      - name: rook-data
        hostPath:
          path: /var/lib/rook
          type: Directory
