apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
      - name: rook-ceph-operator
        env:
        - name: ROOK_CSI_ENABLE_RBD
          value: "true"
        - name: ROOK_CSI_ENABLE_CEPHFS  
          value: "true"
        - name: ROOK_CSI_CEPH_IMAGE
          value: "quay.io/cephcsi/cephcsi:v3.11.0"
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1"
        - name: ROOK_CSI_RESIZER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-resizer:v1.10.1"
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-provisioner:v4.0.1"
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-snapshotter:v7.0.2"
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: "registry.k8s.io/sig-storage/csi-attacher:v4.5.1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOK_HOST_PATH_OVERRIDE
          value: "true"
        - name: ROOK_MON_PATH_PREFIX_OVERRIDE
          value: /var/lib/rook
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: rook-data
          mountPath: /var/lib/rook
      volumes:
      - name: rook-data
        hostPath:
          path: /var/lib/rook
          type: Directory
