apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
      - name: rook-ceph-operator
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: ROOK_HOST_PATH_OVERRIDE
          value: "true"
        - name: ROOK_MON_PATH_PREFIX_OVERRIDE
          value: "/var/lib/rook"
