apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: authelia
type: Opaque
stringData:
    jwt_secret: ENC[AES256_GCM,data:ZX4GqTY70GuSJk2hfwx1sk0+I81HEWAlnNrQ5FwsjJt2sLIGejzKMVknXRD/bHEqHEb6fJC7GH+apH0xTofsGQ==,iv:BdGyBLqf/ayjJXG026B3+Y4O5ceXg6RSNzrhZxiYQ1A=,tag:SuffDBpnrfFNbHQQPM3zow==,type:str]
    session_secret: ENC[AES256_GCM,data:fLNlJBpQ4Cj25JYLK5lTwWvWmjHsVAh5Je43x5EI3ar1Z/XEJ8/BzS83jDnyjoQdWWGinc1Brs1odmF1L3W0SQ==,iv:mZ7R5U0/jF1xB5cm4L07h5/cFUg2vZCy6k0pMcSsOlQ=,tag:oQe6JWP1G2ULskc1rTmV/g==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:BbWVaNK/agqykYKP36+GRgAZN+gfslwOrenpyc58lb+uDGe0087NskBf+QqOzOVETyzlakuF5sYI/krFL5uuxQ==,iv:bOBUSKCEqctPerkYDnCNdpHGuNHLzVSPBl3FHyH9ayc=,tag:pqLvSXvPfUqDgtO7GcweBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-22T15:18:20Z"
    mac: ENC[AES256_GCM,data:+8Bhi+tRMrJoiJ6fpDUYiSYm/Va8td8vPSRQzF2CoZC6fmdRd91Nz5RmXC9xiRS6vmuskxOrD+GxZFurLipa9J4Whggsiv38gEk9k8AaSPFdXbePFVPGg8qajFDtjQ/2NkVOybyiKil8WEbG2chKArrc7DDHetnDs1lCurZwmwo=,iv:i+PpYMISlnvvNJER5mtW2HcTCFJUHokqszoJ5GZCrwk=,tag:omGMecCAZl4fG4BGRJNnSA==,type:str]
    pgp:
        - created_at: "2026-03-22T15:18:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/+LVCZvHIcn3rUnvEKWb20NdYNwYI7b1+RJoLLyBoQJjVg
            LElSpZFVLMD6a8G57eBbfQT2ZW+8WYWvOtWd9+snzC6R4yc16chlgTsWrhODCnVX
            Btw6ZhQdfMY6lFD8tVTfVwAE1nBsxQfTZKiNnvz1zIc95OIhZWjVYmpeq7KqpewY
            hFU2CwmtBV+c0X79Wof9qHrSirLkbamri/6dHvvGzp3SuIaH4/LswytyCKUQMP9E
            Y2c0HDxLUlxed+GvxAXLmvcWSIjeeZbc851USp8pmvf/b4GxQHm0hnWejAXNyP2+
            dYUgezyJR2IxP5/SLZtzdExhPt0aE4Q8gEj8n3SSkO2+YoOodRjWSCiMxnNw1jUX
            qy936DGqtfKqLQ6rcwMENt738+lW7dgk69OUtlY3UckZmNMaCdR+qiy2fmRfdY6O
            EWzrFmHe0VMgPuh/1D7hYZafseOTzM//zWDj1dEUZVB87SU1PYWzu4k0KP2vLqTJ
            TN3aHnc8xlBAeOKW1KgSgCcLiHmZrzQmbmO/M6RHSdfcZOJ1EwMYYDRS8qNkur3Q
            NUmK6wXItStUQw42YoiRVkGxXHmXPr408lNNlpzidKnj8AphQ7IUOZclV4n2JjDb
            aG0IAOIO6kaucXYgc50HhQzgMtaLHC6p6LMGbW6ucT3G5Ypa5U0hJREpvc5lSmXU
            ZgEJAhDNv3BqyEG0cbuBpwKPvYq52arR3p2/p/b0BCCKan5lq3gcOmm5cCYZpibp
            aMsYARzyOd+GbHAHiCweN3A4L9sgQRBlTxueESY6qBgr1heiHeQj/LWrKC8AaJt7
            jZ+Ju2LLJg==
            =wFqP
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
