apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k3s-kubelet
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: pp-proxy
    path: /proxy
    params:
      module: [kubelet]
      instance: [k3s-m-1]
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    honorLabels: true
    relabelings:
    # Use the node name from the instance parameter as the instance label
    - action: replace
      targetLabel: instance
      sourceLabels: [__param_instance]
    # Set the job label to match what the K3sServiceDown alert is looking for
    - action: replace
      targetLabel: job
      replacement: kubelet
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: pushprox-kubelet-proxy
