apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pushprox-kubelet
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-pushprox
      version: "103.0.1"
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: kube-system
  values:
    component: kubelet
    metricsPort: 10250
    serviceMonitor:
      enabled: false
