apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    port: http
    scheme: http
    honorLabels: true
    relabelings:
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_ip
        targetLabel: pod_ip
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: instance
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: pushprox-kube-proxy-client
