apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      pluginsDir: /data/plugins
    serviceAccount:
      create: true
      name: headlamp
    extraVolumes:
      - name: data
        emptyDir: {}
      - name: frontend
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /data
      - name: frontend
        mountPath: /headlamp/frontend
    initContainers:
      - name: init-dirs
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /data/plugins /data/tmp /data/.config /frontend &&
            chmod -R 777 /data /frontend
        volumeMounts:
          - name: data
            mountPath: /data
          - name: frontend
            mountPath: /frontend
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
    env:
      - name: HOME
        value: /data/tmp
      - name: PLUGINS_DIR
        value: /data/plugins
      - name: XDG_CONFIG_HOME
        value: /data/.config
      - name: HEADLAMP_CONFIG_PATH
        value: /data/.config/headlamp
    ingress:
      enabled: false
