apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      inCluster: true
    staticAuth:
      enabled: true
      tokens:
        - token: "Xh8et5UMP8G3OUJlMhs+e3zGzTeBFBjNTuXhGl29LP0="
          name: "admin"
          groups:
            - "system:masters"
    serviceAccount:
      create: true
    ingress:
      enabled: false
