apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      inCluster: true
      extraArgs:
        - "--plugins-dir=/headlamp/plugins"
        - "--kubeconfig=/home/headlamp/.config/Headlamp/kubeconfigs/config"
    env:
      - name: KUBECONFIG
        value: "/home/headlamp/.config/Headlamp/kubeconfigs/config"
    initContainers:
      - name: init-config
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /home/headlamp/.config/Headlamp/kubeconfigs/
            cat > /home/headlamp/.config/Headlamp/kubeconfigs/config << EOF
            apiVersion: v1
            kind: Config
            current-context: default
            clusters:
            - name: default
              cluster:
                certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                server: https://10.43.0.1:443
            contexts:
            - name: default
              context:
                cluster: default
                user: default
            users:
            - name: default
              user:
                tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            EOF
            chown -R 100:101 /home/headlamp
        volumeMounts:
          - name: config-dir
            mountPath: /home/headlamp
    volumeMounts:
      - name: config-dir
        mountPath: /home/headlamp
    volumes:
      - name: config-dir
        emptyDir: {}
    serviceAccount:
      create: true
      clusterAdmin: true
    rbac:
      create: true
      clusterRoleName: cluster-admin
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: headlamp.local
          paths:
            - path: /
              type: Prefix