apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      pluginsDir: /tmp/headlamp/plugins
      pluginsUrl: https://headlamp-k8s.github.io/headlamp/plugins/
    plugins: {}
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
    env:
      - name: PLUGINS_DIR
        value: /tmp/headlamp/plugins
    ingress:
      enabled: false
