apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v0.28.1
    config:
      inCluster: true
      baseURL: "/"
      pluginsDir: /headlamp/plugins
    staticAuth:
      enabled: true
      tokens:
        - token: "Xh8et5UMP8G3OUJlMhs+e3zGzTeBFBjNTuXhGl29LP0="
          name: "admin"
          groups:
            - "system:masters"
    env:
      - name: HEADLAMP_PLUGINS_INSTALL_ENABLED
        value: "true"
      - name: HEADLAMP_CONFIG_ENABLE_PLUGIN_INSTALL
        value: "true"
      - name: HOME
        value: /headlamp/config
      - name: XDG_CONFIG_HOME
        value: /headlamp/config
    serviceAccount:
      create: true
      name: headlamp
    ingress:
      enabled: false
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
    # Volumes for plugins and configuration
    volumes:
      - name: plugins
        emptyDir: {}
      - name: config
        emptyDir: {}
    volumeMounts:
      - name: plugins
        mountPath: /headlamp/plugins
      - name: config
        mountPath: /headlamp/config
