apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      pluginsDir: /plugins
    extraVolumes:
      - name: plugins
        emptyDir: {}
      - name: config
        emptyDir: {}
      - name: tmp
        emptyDir: {}
    extraVolumeMounts:
      - name: plugins
        mountPath: /plugins
      - name: config
        mountPath: /home/headlamp/.config
      - name: tmp
        mountPath: /tmp
    initContainers:
      - name: init-dirs
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /plugins /home/headlamp/.config/Headlamp/plugins /tmp/headlamp/plugins &&
            chmod -R 777 /plugins /home/headlamp/.config /tmp
        volumeMounts:
          - name: plugins
            mountPath: /plugins
          - name: config
            mountPath: /home/headlamp/.config
          - name: tmp
            mountPath: /tmp
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
    env:
      - name: PLUGINS_DIR
        value: /tmp/headlamp/plugins
    ingress:
      enabled: false
