apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: '0.28.1'  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
      interval: 1m
  values:
    config:
      pluginsDir: /headlamp/plugins
    extraVolumes:
      - name: plugins
        emptyDir: {}
      - name: config
        emptyDir: {}
    extraVolumeMounts:
      - name: plugins
        mountPath: /headlamp/plugins
      - name: config
        mountPath: /home/headlamp/.config
    initContainers:
      - name: init-plugins
        image: busybox
        command: ['sh', '-c', 'mkdir -p /home/headlamp/.config && chmod -R 777 /headlamp/plugins && chmod -R 777 /home/headlamp/.config']
        volumeMounts:
          - name: plugins
            mountPath: /headlamp/plugins
          - name: config
            mountPath: /.config
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
    env:
      - name: PLUGINS_DIR
        value: /tmp/headlamp/plugins
    ingress:
      enabled: false
