apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/headlamp-k8s/headlamp
  secretRef:
    name: ghcr-auth
