apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pushprox-kube-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-pushprox
      version: 103.0.1
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    metricsPort: 10249
    component: kube-proxy
    serviceMonitor:
      enabled: false
