apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: '2.15.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.11
    
    env:
      TZ: "Europe/Stockholm"
    
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: kuma.local
            paths:
              - path: /
                pathType: Prefix
    
    persistence:
      data:
        enabled: true
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    
    # Node affinity to avoid master node
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - "true"
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
