apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: '4.0.9'
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 1m
  values:
    # TrueCharts specific configuration
    image:
      repository: tccr.io/truecharts/uptime-kuma
      tag: v1.23.11@sha256:a0d6b0b1e1d3d0e0c2e1b9e2f2c1b5e1b8b5e1b8b5e1b8b5e1b8b5e1b8b5e1b8
    
    # Set timezone
    timezone: "Europe/Stockholm"
    
    # Configure service and ingress
    service:
      main:
        ports:
          main:
            port: 3001
            targetPort: 3001
    
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: kuma.local
            paths:
              - path: /
                pathType: Prefix
    
    # Configure persistence
    persistence:
      data:
        enabled: true
        type: pvc
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /app/data
    
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    
    # Node affinity to avoid master node
    nodeSelector: {}
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - "true"
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
