apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: ixsystems
        namespace: flux-system
      interval: 1m
  values:
    # Basic configuration
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.11
    
    # Environment variables
    env:
      TZ: "Europe/Stockholm"
    
    # Configure ingress
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: kuma.local
          paths:
            - path: /
              pathType: Prefix
    
    # Configure persistence
    persistence:
      enabled: true
      storageClass: rook-ceph-block
      accessMode: ReadWriteOnce
      size: 1Gi
    
    # Resource limits
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    
    # Node affinity to avoid master node
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: NotIn
              values:
              - "true"
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - "true"
