apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: mattermost
  namespace: flux-system
spec:
  type: slack
  channel: flux-alerts
  address: https://chat.k3s.nu/hooks/95z499na3jr5dm9mhedccydd7w
