apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: camera-bridge
    namespace: openhab
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:d08mrdrkpmMhEaoh12XQ0ii5tc0659MBe8vNerFhZdvr3jwyze/LSQC7qMl1gpBemhwj3cQQUwJS0i48ZQ==,iv:7j4O4Tcwz+2bQHtYWIlKrw1DIt2gPAMpCkhBZiTwQkA=,tag:Ont6i0YRTGG7u1qYFrV04Q==,type:str]
    go2rtc.yaml: ENC[AES256_GCM,data:+6/P1IlpnZebox8+UahQ9HNW1MYcvoWN1H7V0qUyAy/g8l5k78CDwKZdHNbl9fYf8bBZxLj0gI7Y8MuNi6ZfqNwmJ3XVB3xP/FbzZm/l/1WcFnv/Y1xqkCTq7mnIwPgPMMxrdIB5veyyLJuwImZPIzcecDM3hyWSKbX3bgWCCN1fqH8leLPr+xS6TLJxwRHv+lmTsZMwbuS9BkIm7gH6N3cqlTRmHLsQsJaEyJ8HcXmtFYwgtLVP/oIs7h9MOii8BTaRq6DVVL3UiQgs7bqEHfmQFJznK7RDKvWiagFsZZFEajTIUzqVrhrRv3urgnnPFitTZKjVmFOpu/GmrzXH1vrPHyIKOwvHR8z4TOjibqZ8fDQlt6D40nBlt2JHaBBeiIsLiLUK+DrIJBmB6ockjrxySPxmZ49dfDhhSEyUyWjxgZIFb4DkK0iwEv+ZDPr7dW2l2JpkMkk+zZmMeCzBL5D+BqwN5Sc11cmKtJYN7kSP8wjbQJ0OCq4F1kDMYphc1fvRXYFjMCY66n1QxW7gSXgWMiXLVuSisAKwDZZqaP4fv/85R1xY/TND2W7srfm2xB7aiJa8dRdqyul8W5hTsalyhPfVg1HWwNAZrQl8CNDtuMi74lJYVqI1G1tmzrWOxMw3q5CcJZ1VYf4x9k3EQWFVFJC/Pdsv1MYrw3PW5mw7Tw/8nNICA8J9s7RfM1kmk/2n8nOzHj7GrMSFcvoOIBbkL5esUC3H4Mu8jLcoHyrc7TS9hxJCmjp/Jqqg/B6Z6v5MzQ29JO+zBxKsA9RPy6AO4V+5c3jLbmNPCXJiry6Z7wNScDfyNtETgDSgxqZGyrTVyZI0tsjo3Oi9JN9F6VSkCDtOdlT/n5Aazw2KuQgM6vtwezA+cFvv+BMinikwz4zk1ctPbYz1DGiO6/20+3cUdQtXtci+zQS6xhLUoSYo3EQyzAQ8+ejVYUe94Re4nXey2UtcViYg3+KdPYdQ/sSf2vzfPXMDchTgS5O+ne0wELijZM2dgNoRkXJPVPaK6O2VEi7SpCQVjHkXdxyxTy/P4TtUg1xmf5J1oYFi+tHk0IN+blMqCODHXae9WKy026YjA2rFdTbsYH94oP0yfm6dqXBw/LbzYkW/89mtHJu+RqheA4g0MxGpg1WUxsd1hq7sGOgc1kWSafFwBuCL6PC2JqIzco4JuujoXWBG2Ef2EQgfJIbYgG0ZqzULiXARMnQi2qpoJGvaodYUAvtU0GES4gQtKAU+Iky1QZMv0xqnUfOYF+tGiYZlUae0b1fFY4tzJDnjsIM=,iv:JuohzgQWn0+lPTsQsgnaW1ZbVxHwVpNBXTcZ7ViBHsA=,tag:LyGe85me8LoahrUgiJ3+hg==,type:str]
    rtsp-username: ENC[AES256_GCM,data:/5Swh7qQkg==,iv:t5Eo6gcyEm//mK3GN9RCQxG91lu93/TKx2s/k/zLaZU=,tag:4POXtZKVjCgMHCiqZy7u5g==,type:str]
    rtsp-password: ENC[AES256_GCM,data:/94Z7i+Wl4Cx7U6SubleJqC5Q3vIIvXN2pzpEz73esk=,iv:29ZIoVuz+M3SekzAoDbz+6Vz9CrVSP+l+pkVuo6PrYQ=,tag:dGOxYrC8MMF752zOkDh6Tw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T14:00:33Z"
    mac: ENC[AES256_GCM,data:4X2GlyL380GaP+ivMl/ekI4awBQk3zz/NZJijedslmkEgw+wlXIfphPkpfeDMlnX5bvNjIdBVubKxeOVoXGL/QqgwFP7EBjAPp8XnGuBXnei1QeG9pyuVuk73rHh4gaONrPGkpT1PgirSr9/rQ6Fnu4VFF4MzQ0JgVoymd6PXXI=,iv:rMpjgyweyNAf+552hVRY+RfFCsjjEdqO41fdLTacLAI=,tag:OG2bJ6pdP0XfOEZmEb4C6w==,type:str]
    pgp:
        - created_at: "2026-09-12T14:00:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ//Ww2UFHS70Jy8jsS4AO3KxVdi45sJSkyliTZMasEb7roV
            1++EHrtmdtllwkMozS7J+NtFkdIMYi4eEeAl6CkhCN6DJYA+TwRDfYcafn/y0FLp
            FFeslOPS5JxG/jXG2DDoY4niEfR3JlsWH53Nu/hJBj0krYg92b1dgTfRNUz8tqP9
            DRCg6GMgIlV46LIX0np8JOApobIH2+RgsjIYpIZNFCcguYAccbZuf0HchbmD5lSd
            2uhB3YuoxMWXwHAeUiCjRyjr13UstxDIDjShJqeP8Xk1iIHfiHIVOmW93MsLJpUL
            tbopOQF4cOBttsqA6F5wXM5bN5FSFwEb1WV8VaaKCf+1ukGJh0BzHkJyjRY/xw9k
            eaXsZtf6gtfboIW/VBUIPePWwu5Oyq65c4YAn2eD6EkyuJvUHxVASJQMAruAiYJB
            7NnJqkp2NQaMILuQJP1jOoYjlPg4TI/ZBUsF4ERGH7LSP2jqsGZ0p63VyJJxelQv
            pNkPcordRaGIVxPL0RNQADj/AZPb4dya0znADKLIGBaFQKXruYOLADL+TjBNMHJA
            q8dT1DchNSXdmOJH/26VWXo+tpHOYRpYDEKu7waG3Yy7/3GAZK4TBNN0QOcrBMAY
            D7liwkgQEAWOHHo6eyvveIC+SO2EhAZN2FBBYUyqx2Dgm33ljWwBDhANTh4wzsHU
            ZgEJAhAnWoDeKDFJhqWjTS3XmQXlrYruVVUDeAmSHjS4Ghd73zqmbdsoVneW7RFV
            HsUIphmvF6Gm9MaIe3GoPJdmbvbuS0TeZwzb0q0WpgDGhNbDnwclL9wphT++LHJi
            Y0WeUY1KGw==
            =Br42
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
