apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: camera-bridge
    namespace: openhab
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:upMTfaaXLP4t9jtu4DgXJ6wiOitVhHCxcygJnsOQdd/Hm+fwqRNVWzJ4l5kcyd0nQ4LxyEV8RG0Ve8FlLQ==,iv:abqluxiDvKuze3huZemmyHXX5HwpS18Gbp1/46kqjNY=,tag:HK46dCcpk+XI1sF+LPZDxA==,type:str]
    go2rtc.yaml: ENC[AES256_GCM,data:5Dt1Q/edBg1myD0iF5A9XlbRjXQ0ERkV5BKjQnCyy8qRPC6vfKogVIVwKxIj/qwbwgtHstEVc0n9cte63fgtbfRB+U1f6mf1cYcmGQOIiUNrkTDJ5oAx0h0ClQswl6ZUwtfeApW+aqIz2c84WiTgkpSZsqQtvQKbBHJykQCHN2AJ3EmEczCiMiqPr+Unv4MzptM1sRgYs9W82yxjK8Yve4Lxa/0ViEaMb1ymBR3z9hF0ug6/xFZGkpXiHkkB3aU68rftwT0VYA8S7zZETGLYRZd61PMAZxW5XKzdoyN0pHLMTB8QY2i0UqHAoRYmK64x90/aiFfcgoXEAd4WK9rz3Q9XJgzFr9fVRjCobIyJd/FeMeZKqIZ61VIOdhnkMS2V9iT+Eu9oFgkJrV5C5mDYLRB74z+RF3Mferda0tVP2O4vghKW9Mn2mhSpMZfxbg1bjKDdZrHi28Z0cRoAIcQP58inhkH+QUjCRqmDTAA6jU39DpoWeAmt4jBg1fYWNX6xY9uNwa6idUQ5ETY1yo/zfC+0nAgQbAAbU4vocHyByuXO+39Tx7Oly/csemvNss1JgurelhadQgYqAJqBWD0jHZFi6rnl2nCmlaI7yHlsFmg9OEsiX1qiAkXs9ujLFfj0bwqGXQ9cUYI/x9GEQMjkj6mUYYseFWC72E4DexukumYoyNU6XyD9GV8dl3agWX5X0QzUxiEZtL8qgwuA3V0RJDWpn0R60N4dt82wHczJAZgArPyKfQ/jqmd17jdNjDGU5Vk4RwnDjb8vYhCiHauOMHZiAUN9np93SDZqoMJt/UyCGgnFcwcE5YzhBb3ur+GJ9l7YdHiYS6obALnRtl4TrtU7LZByRO1FuZmMTe+z/3sz3kcZpGEiIALn9ZCWYg8gstTLk+fSmZoGFL30nyLyWmcf2w2VPETz40a/EiJiL/YXnO3m7tX8YQL1eRn8zN4N4AveeeObYeRUOFocTsZdM1Pz9LRM8282z1/YFH/AHXSR1v25NmVeOw/25VZnb/rVh/AiK8dbuzxWObx5xJIhh1iMtq0FF2pfs7V+oKHsNlhYT+/nfAFhnz0gF2D1ysHnU7ZmHbq3/kYo7q9XHWaiKj+xgl7/3XCrE5nQOWHtaeu940V2wdj6JYeEsL3mtH++u/nfyesO+zDxXmkkV/R3xKiGSvHaOCNN3zuRo9GeqToQ3W+K4WIcDNflKNoX4S+V4/8YBZpeZ5Q5dfNUng/pxEpSo17jww==,iv:UX/7YgM/ip9XEy6MTOx+lah3n8vMw2JXCu3TeYJFWHU=,tag:t+6PJ02Nyxl9cZz6+pc96w==,type:str]
    rtsp-username: ENC[AES256_GCM,data:jYAT4Agjig==,iv:qVIKW05h2wv1VeOiS5eftVCnV0brEqgROgkeS6cxmLE=,tag:rzCx+14pfGJVtygm899R+A==,type:str]
    rtsp-password: ENC[AES256_GCM,data:CzyxEkFG3cVisABihfl5agz/W3CSYn0/UjVa54BuOUk=,iv:d0J5+u+SsNscrH/66LKypATO3kdhz0jwwWwgHK8CdpM=,tag:CCfRCiib71qm50ct2spLCA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T13:59:28Z"
    mac: ENC[AES256_GCM,data:HJR+TP7DjdkgkMF7RrvkeMdbCjvEdLBwpc2Tifbf5shWbvuP/DRaM7dZqn4jKAuQBVKTdxRvbR4iXs81m0kv9mevrmLrv7xUUdGLWil9xJeJSfoInQUe9XOCtOH9Xy/rajcWDH2Y9urOzhm93KIxVdQ1LmBZkKDtaq+EqBgmBxg=,iv:XY+e2VZvG4LFhkw8mg2A8N3MMdd9WgwPBpyT2i6WHjM=,tag:SqaSJiEDJkzV6aALAg6X1g==,type:str]
    pgp:
        - created_at: "2026-09-12T13:59:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwARAAqnrrpU9CIdYI9YFx3G+dCvQZ3XdqzHGZW3IEPYJtZ5Li
            KTOhoXgyx03kWYHaPyxVxtzJgWkRd8zLtO0KlDu8SXFZZLCLmBSZKo2N33Oc5aiY
            hZyE+qPYZqMFSx6PDmRxoc3wABCIk60lIzNiqg93uU2MANnJZXYVnH4wlUdYdMj3
            jzrEtmy0udyWuxHUyb/eT+kk5WZmG0JiKbPPD2I+Hz1EYaT3TaxLBP41KSzjt2zv
            NUGVY3diDsTuw5qtpCQREhSVG/v1fYbGW0QxDCiujYJM/yzJjG1Qbp2stI2FU1p/
            7Q0xcM9hqlV0pTm2nMzqarVR+UzkJSkHg/Rlzk+eeQ4qKAmG+hGF2b5IdnQsh1bY
            fmGNlHAqatErZJnGMKEz3w2jOmTjrVMzJfL4cjli1GeZLx9eG7BrWy38nGUAc4XY
            JzQch9VDzvYxb+/dKZ2mps5bH20HMKoSG9LA4SMw7hycvnlPOMfQAPkr0fDH+nHo
            aKYAc4TNW7ewScQEou7klpvHaKZzfvGPibk5w81g0ldM4+hH0ixjWGsAR29PBwZK
            padvDSzZygr3iYuELXPiq/KOKqPnKw41o3DVYMYSQOQeeqzbIF3RIAC9wQziRlQ7
            gOI0cKq+t+B5ziXL5yuqZ7pW6kqdHgptyIqocUpA8km0HR514c7yYWB7XXWWtFDU
            aAEJAhBTuEh0hZY/LPg0CgoIL407YDxO/nVeSefXUXyeXeph3fhnKqzvBYDYejgL
            yFZUqJKNDvXvP7ix21wUbAfUDOr4FfHONZK2M/HNFb38RmPujFzwRUewsy9CHEud
            6RqE/q7gaMFJ
            =DZyr
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
