apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: camera-bridge
    namespace: openhab
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:DcJ6OWPiCl3T3BxGQsH6uhaceG/ZGRYZnuRfeaA3QdlZy//aF6CZ1lPvUU54RnqmMmPOrs/8QiWY2I1wfQ==,iv:dg3MyI8JiNxFFD5M1oxKW7gm5sDzsNUQEnHrwUWXF4o=,tag:cJR88mS7bARoddKSi/oVbQ==,type:str]
    go2rtc.yaml: ENC[AES256_GCM,data:5q7OUR1z0DDUSbKEQn4J9eryp1EahB16o1B6kQOo/6tZIT8JcFgd1scgyDj5dmfLRj8n48056Wnxddw+dyPvzNy0bxTg/TC4SmuOONzswQN8L1KHcMoSrn92BcYFZhGd/z11Rafm1qJRBam5fv2ioEQKUMv/2EKKpZC9+LIoW77W3xGaqmWY/NH1h0hCldiMsXrhNbTxfXZ0fHOb08VUBZbsITG9CJyrm77yp4Yj2fjjeaPKNTE45ZL/2Hlwedb2ThE7emeUQb+rNXRY0Q51umJQEA7mwgxkmlsHS3u0EHHWpN+h4ZLgFBwIPlmfgeW0sjWUa5TFppJlGSTrKACXqQyeqyrlJ6hYFlINXN2844pXkytBf4f+0UBDCDUThCyIoMwZTd22PBKkda+kOAQuSdNR9p+PIkXmiZ+dZqK6r6AHQ1OV0HvOLfLA386KEA/MOFVqQ0qZCAKD722QKt6DGgwE+xaz9AbjkDLFnsXDmxNbzeXoq+KsHTrQne6IbEDZCkolhny9ZxTojDdg2jFAreqMyDfRkUpHKumbL9PdAicWwyArNvsWn00JIcCz/QcLj9OU22wtqpRa9bi+R3ociE3nx7BO6CfqAW9tm7prVGw2baPLwirUSo/t/LB8XNRz6bJgex707rGIaWGr2wsVdtlT5H6ZkaTXdVQ+P+vHOxodFgTjbnr6ZcZofpFNxDPDJCrx+5KR20SfLHKVBeDvoV+q3xCfyra+XAE2DmG0SWTwvyuehsKLmPU+D3r3qZcdzpO3T1x1Au9ch5tjc51Adulbc9L2IDUdjx5eKeJrBJmGp+0Ua/zrLOpPPh9Bgj8glbUM0JyxSRR6mIyT3ryOeaEiMmg/tEiG/Nrh50O0s4Yb8oipiBsR/ywsA0P95hnyykbYKI23mDxutPVD8FFxguxvH9YAwG/X4HiLQrNzOFiSSp/t3JFN2cbiiHSaSMGMPJbTkg5dAVSvpsNlBMCYt0DxF80FJh9w5E1JXnlFVIYu27dOfDdDExaAW4ya8wGDdshKmaid9Tv9V746jUQyOcezFbQG8kH81kRcvCKZS64=,iv:nvB7WATOSSOKvqLBTSdmm5z3ti5UUBegaTyq4voSLzE=,tag:8P4tM3OyjtISKcjwXFtrUw==,type:str]
    rtsp-username: ENC[AES256_GCM,data:0jUxayCyZA==,iv:wPNENYb672n1dNvnkaLyfhJq0VMe+NH0Qezv0YmMRzc=,tag:QOfZ/+1LbeAMaXVj04w4Gw==,type:str]
    rtsp-password: ENC[AES256_GCM,data:EmiaZCO4b3fMF+FJvwGBzrfxzjyAEaAs/B2/uFZwUVI=,iv:deJjsMgrsL+QKqSKkqfRY/7Me0rjt38molygsSRhG6c=,tag:kGmFIJZn3ofesv9GINC5jw==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T11:41:18Z"
    mac: ENC[AES256_GCM,data:0DDDmP+T+VpG4tpyw3Txx36Oq4v8spu9b2T+EH4KhrzG3JL6Rjj0pO1KLp8PaUaXP/xwX/2mE3/YEeqTJSjpVzptVT1DujRPxIL9vVtFCx07P/FCFOcPj6kVsn+r85wtLR2x0nMPxV317pQYdRUrQjx2V8JJEIOjQHe8XK9BY8Y=,iv:PRlr4BIg3Y+ol6AzonQ0/qcbmIopWEOSmBURVlUKrAI=,tag:/hKTPSH/h9/YY/jidJKY4A==,type:str]
    pgp:
        - created_at: "2026-09-12T11:41:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/+Js11y0jDMZ25Eokg4hyVwF5odVj1XGD0/Is5B73YDE/o
            ztDyT91nWc5hefC/ackEoIgxIIwU3IZUqrCr24UVpLPhWuUGR/+rffO6qwsf07/p
            71mtwXVSItaGZBU6jEgPETbdnF9kyCfeiCNkbtwVsIYZzWb5z4xXUk4Za+DPzzuF
            khvapqd+M13yOHhjPmwpAM43les1i8AhMI6yELK6rsymbdSpjNV9fsyXaD3BCxWO
            0OK0KJfh4ch7b8wtZOC8Y3HYJl41HMK+II6RR3fIsESISXqYLPTD8GL1PqWWZQaG
            uSpQgTS1CAdldyU0x9Zn2XeZJQrdEwVukUQ9XR0lt28h8b4BPEjGqZUB5poeHtT8
            uzGQtba+Jy0FKL+Oh7xhV09GJJjAFaFv38YmYWXThF6s13nkCCpco1f/wGAnI5Fu
            fZJpgPwxKqY2pREN+WcMMbHQCvN0aP2qYzz5VH4y42G65KATAL9QB66PoVZ5UGS0
            2BpTcABaMW06OcmyWe7ICIYHTwB/falFCsV8vqYRXYu9784pqa/X7sCaF2XtUYdj
            fiv91wA1ccgclYXg+AIQ29xc7T4hYZeyIk4td7M1LlPnCSgU2xPErWPzMKsQKzdd
            AtIPC3J++Nx2YnQJx7BUIovCzJMf96C8qmed76COpwTLR7PaUIUvll8nMehht6DU
            aAEJAhBIvq/CCpvn7DmJdFk9U03RvYSzRpi3eYXVLxh0Ku4ApkgWZX/gMow8H0ES
            gCe1vAfqgQmE0drCd07MrT6Z08cA56AQdDiAeD64MK11Us8pMAQazgwbHDTPjfSc
            uyJxLIcyNyg7
            =ivMj
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    version: 3.13.3
