#!/usr/bin/env python3
"""Generate clusters/production/apps/openhab/camera-bridge/openhab/page-cameras-landet.yaml.
One widget per grid row/col (an oh-grid-col renders only its first child)."""
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "clusters/production/apps/openhab/camera-bridge/openhab/page-cameras-landet.yaml")
NL = "\n"
# Ordered groups; each entry: kind, card title, item, url/thing, still name[, ready item]
GROUPS = [
    ("Huddinge", [
        ("battery", "Carport – C425", "C425_Carport_PermanentStream", "c425_carport", "c425_carport", "C425_Carport_Ready"),
        ("mains", "Arbetsrum – C220", "C220_Arbetsrum_PermanentStream", "/ipcamera/10ce3f91aa/ipcamera.m3u8", "c220_arbetsrum"),
    ]),
    ("Landet", [
        ("mains", "Lillstugan – C720", "C720_Lillstugan_PermanentStream", "/ipcamera/c720_lillstugan/ipcamera.m3u8", "c720_lillstugan"),
        ("mains", "Lillstugan – C220", "C220_Lillstugan_PermanentStream", "/ipcamera/c220_lillstugan/ipcamera.m3u8", "c220_lillstugan"),
        ("battery", "Landet baksida – C425", "C425_LandetBaksida_PermanentStream", "c425_landet_baksida", "c425_landet_baksida", "C425_LandetBaksida_Ready"),
    ]),
]
def row(comp, cfg, visible=None):
    rowcfg = ("                    visible: " + visible + NL) if visible else ("                    {}" + NL)
    body = NL.join("                          " + l for l in cfg.strip(NL).split(NL))
    return ("          - component: oh-grid-row" + NL + "            config:" + NL + rowcfg +
            "            slots:" + NL + "              default:" + NL +
            "                - component: oh-grid-col" + NL + "                  config:" + NL +
            '                    width: "100"' + NL + '                    large: "50"' + NL +
            "                  slots:" + NL + "                    default:" + NL +
            "                      - component: " + comp + NL + "                        config:" + NL + body + NL)
def block(title, rows):
    return ("    - component: oh-block" + NL + "      config:" + NL + "        title: " + title + NL +
            "      slots:" + NL + "        default:" + NL + "".join(rows))
page = '''# Main UI layout page "Kameror" (uid: cameras_landet). GENERATED by
# scripts/camera-bridge-page-gen.py - edit that, then deploy with camera-bridge-page.sh.
# URLs are same-origin (relative). One widget per row/col (oh-grid-col renders only
# its first child). Every camera shows the latest still (conf/html/<cam>-last.jpg,
# written by cameras.js when a stream stops). Battery C425s: tapping the still sends
# startStream ON; the player replaces the still once cameras.js has confirmed the
# playlist exists (<Cam>_Ready); a red button or the 120 s cap stops the stream.
uid: cameras_landet
tags:
  - cameras
props:
  parameters: []
  parameterGroups: []
timestamp: Sep 12, 2026, 4:30:00 PM
component: oh-layout-page
config:
  label: Kameror
  sidebar: true
slots:
  default:
'''
def mains_rows(card, item, url, still):
    return [
        row("oh-video-card", f'''title: {card}
footer: HLS via openHAB (~5–10 s fördröjning). Tryck play för att starta.
url: {url}
type: application/x-mpegURL
startManually: true
startMuted: true
hideControls: false
playerType: videojs
posterURL: /static/{still}-last.jpg'''),
        row("oh-toggle-card", f'''title: {card} – permanent ström
item: {item}
footer: PÅ = strömmen hålls igång hela tiden, start utan fördröjning. Visar även PÅ medan någon tittar.'''),
    ]
def battery_rows(card, item, thing, ready):
    return [
        row("oh-image-card", f'''title: {card}
url: /static/{thing}-last.jpg
refreshInterval: 60000
action: command
actionItem: {item}
actionCommand: "ON"
footer: Senaste bild. Tryck på bilden för live (batterikamera – ~10–30 s start, max 2 min).''', f"=items.{item}.state != 'ON'"),
        row("oh-label-card", f'''title: {card}
label: Väcker kameran…
icon: f7:hourglass
footer: Bilden kommer när strömmen är igång (10–30 s).''', f"=items.{item}.state == 'ON' && items.{ready}.state != 'ON'"),
        row("oh-video-card", f'''title: {card}
footer: Live (HLS, ~5–10 s fördröjning). Stängs av automatiskt efter 2 min.
url: /ipcamera/{thing}/ipcamera.m3u8
type: application/x-mpegURL
startManually: false
startMuted: true
hideControls: false
playerType: videojs
posterURL: /static/{thing}-last.jpg''', f"=items.{ready}.state == 'ON'"),
        row("oh-button", f'''text: Stoppa {card}
fill: true
color: red
action: command
actionItem: {item}
actionCommand: "OFF"''', f"=items.{item}.state == 'ON'"),
    ]
for gtitle, cams in GROUPS:
    rows = []
    for c in cams:
        if c[0] == "mains":
            rows += mains_rows(c[1], c[2], c[3], c[4])
        else:
            rows += battery_rows(c[1], c[2], c[3], c[5])
    page += block(gtitle, rows)
open(os.path.normpath(OUT), "w").write(page)
print("wrote", os.path.normpath(OUT), page.count("oh-grid-row"), "rows")
