apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:kgZRHrf/JOaJ5EEbOhxbXj8I1kA6XAhmYXzC+s5M/oOUgJVeSvynLA==,iv:xyhfbKLuaz7gGemnaH0EQIGZiJrJI7IlYdiStY80qgg=,tag:LLh1v3RwSBxi2bzqAaer4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-11T18:29:30Z"
    mac: ENC[AES256_GCM,data:G/VKbvgLUW/NfXR7gcR0GxlJCc4ZtzSJfohM++fm9KmNhdBj/eRkFLEVG3OysUsZPoeyhhV71vrM+8peystzjBZmXsv116saOmfqM0QWwh0dkiDUW7d2tOmvQdHPYfqDOly8odCk7Dk7alElzpugBdO/z54sydF0/GREPcHl064=,iv:fBsw1Ai4S2dRI7ly9cdaaRctO4KWa6s88AbmCVseYPg=,tag:Eh4SYiNLHAJrbTQq/fWQPw==,type:str]
    pgp:
        - created_at: "2025-02-11T18:29:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6/oW9tH5TjwAQ/8D83YjHSVzxOMisZN1V8aN1IuMqyOogW4YcBqmgP8Upyl
            SAWFdMWGsNHFe+DZB4m9NO32vccl4n9JNDlVkZk5bVikrGVGMBiCFVzexIrgkuAZ
            PXqy87ckwQIvYKDDkET1pK/tTTwP14r/x8NSqi8FrU33CSQaYf2s/1tUH0UVPwDX
            MEZtW7WAwz9tFhlM/ECIfDO4xkVj0N/Rvg7zMAi5f91h/98HFrgC/4+yveZvANb5
            yrJ3pSyywIHPRBwtk3k1fMcEbFo5o7Ry8+Pwkew9YLnE/vyB27fYCDpHjtlgydEF
            GL1t29HkNGfbtA1U6qJcTziA/73Bs1aLOJQzIIyDtwVoKOzsGcav6AjsbJIKOEX3
            NhjwTaQAeSPXXE1pLvoStut2FI9D72z41DBzIkMBiRUBOpxTieci16XXbjBkT3fy
            kC3ZZiDvlNQrGCQ3CXAPjgHUw5V/ExilVhc9h7hBrz174HXc3v4ESs34L5GN0skd
            fChNYt/Lsk66wI4FSVPPWrNEx5clX0Gus47vp4dtMjV1uVzGqODVLGOKhvFHB5cU
            7KOyqKUXUEN2XvngMuWfRyVpmWH9+3ZI6DFMW9lXhunnee3hSazFv2Q9HGkD1AVP
            DJBkL84WyIKAZUaJxGag7LZfvtsTzGJywnL3a2vCmUnCtbBiW+kBH3ftWtdebSjU
            aAEJAhCY/eweX2A+4uctu1GBELfh15fOHkbzwbd6/Lmwiec1DcbKJenbigHdrr7B
            wESn6E82x+f+aGQIjRllrhtM3KPhyNY3fvKyAirhUwZZE86EGo2y6TsklxSUwS/D
            B9VWWA31CIQa
            =CtJ5
            -----END PGP MESSAGE-----
          fp: BE7CC9C5400AF50610072526D7332A14FB23EE47
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
