{
	"data": "ENC[AES256_GCM,data:tf4eLbfxTk9PxdU0O62P6QUTHZOEzEeIEpTMPUspJVDFfZuHkEvGf2yIhwd+8gRoeFmNGlnno5TLN7WBicdAg+aGKUU6oCaRLTGCIqRa5uDO6eOK8TnXP2khYZpr39U3dzEcxu7neiUZ/JAWYEfOFgtm+eEygF+LGgGvVdWC+hAVlU6Ie2g4N1TXGP8zAMjRQrGguAR7U7DsJ8nv69GHXZNIbOMRuGYUGjCgekMFn3fsjKUIzXE+lxE=,iv:KCYlP19wqlwN4g4y1WXjZl/aKufFCjSGPuNvVtTaXAk=,tag:AbSbEfxoxUNX0qKFrWLUfw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": null,
		"lastmodified": "2025-02-11T18:25:52Z",
		"mac": "ENC[AES256_GCM,data:C/y3vRFSQyhOZilY9b3MIUGSONZwzB+kcd8Rw67xzJp5j0lg/MKqNCmIfWyTndd7OUPa9Mn4YVctAmvVpmdL/krjFNBUdGVMw5JHN7dzOrKs7TntbQsd78irm4fNZFJBwp8y7KxJdFnLP5cZzW/k6qlF1rUUDve69LPyV6eX2ho=,iv:uBivxSKL3Gfxky1XCDKlUb0N+obQkC9XcOvCWiU/PfA=,tag:R3PJmwhxRlVS9LY2fVGFdg==,type:str]",
		"pgp": [
			{
				"created_at": "2025-02-11T18:25:52Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQIMA6/oW9tH5TjwAQ//fc+HmKhq9a2g8Srh7zGytv191R7ZBvyzIe5rw34+gXbF\nqPr757mFsrR4VVHEBD2c+BL+wGjGY5B+i508wK6vWiXGbaRFZV+kHBYq5hHZ6k5c\nqTAPkmq3iLS1KsKY+IzbqdKzaXQTxf/ox73fF5mcHo1t0b+pA0uz2JPENvwGDMll\nxMVCxyM6qYBe7gRhkeR328IZ+4dISnondIRMkf0nVAnZpTgCUfBYHR0eMUU8+OuK\n/mdval6qeYF5kW5KuysvfKLMOTXkWXykYqYE/nH6BHa8pnDZa6+MYABMpsBZIunw\nTYkou74cIoew+ZYkXke+KXZ15HyF1osm0yWKwk0Dsf/kj2joIlVCtOcRNI1ic/kq\nbt/OSeH/c5Tf1yUmGEQXflmhL1KEu+yvRMbgI5MCNJcXuWNd9v/7ZT89w0Bb3se1\nSoDF6Uoa/hkbpVkf9Tct6GY2RNlRDIFPWUyglhgEekmCpgJZa/ALtaHXUROkMT5X\n8o+OqyjFqq3YF0lBsnW9IkR3SCBXNAP/OH/l4VU7FtF1qw7fA4b9H5x6RS9Gxhsj\nDV9rRgePF0WUOV0BWG1mCQbdR1IntNCBJRMe1trpqM2hz9+v54CL/+qdZDj015yx\nnoWaMOySfRhCa2CqKeu03JTGTvOfFhKbUq69E/+zlnmCVhHYvVTDk/azgd6oJrXU\naAEJAhBdIQ9+asWgyJeLYnDRhfa0lbRN36IdrThbghFJF2a8ohHvNejYVcrRrA7N\nrhGfeojUpwRDKDApX8dCn4QERVdBOsxL5FSE9gd971aWq0qFHICaEDzbFqpAGTu4\nFf462gklZOG/\n=uThi\n-----END PGP MESSAGE-----",
				"fp": "BE7CC9C5400AF50610072526D7332A14FB23EE47"
			}
		],
		"encrypted_regex": "^(data|stringData)$",
		"version": "3.9.4"
	}
}