apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: ">=4.0.0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 1h
  values:
    adminUser:
      create: true
      username: admin
      # Default password is "flux", you should change this
      passwordHash: $2a$10$P.fR1PKqHE35bJ1KZ9.jkul2jXbxc4gZHQ5wvyXePqka1Y0qvjUje
