apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k3s-metrics-proxy
  namespace: kube-system
  labels:
    app: k3s-metrics-proxy
spec:
  selector:
    matchLabels:
      app: k3s-metrics-proxy
  template:
    metadata:
      labels:
        app: k3s-metrics-proxy
    spec:
      hostNetwork: true
      containers:
      - name: kube-scheduler-proxy
        image: alpine:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache socat
          socat -d -d TCP-LISTEN:10259,fork,reuseaddr TCP:127.0.0.1:10259 &
          socat -d -d TCP-LISTEN:10257,fork,reuseaddr TCP:127.0.0.1:10257 &
          socat -d -d TCP-LISTEN:10249,fork,reuseaddr TCP:127.0.0.1:10249 &
          # Keep container running
          sleep infinity
        ports:
        - containerPort: 10259
          hostPort: 10259
          name: scheduler
        - containerPort: 10257
          hostPort: 10257
          name: controller
        - containerPort: 10249
          hostPort: 10249
          name: proxy
        securityContext:
          privileged: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
