apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-controller-manager
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    release: kube-prometheus-stack
subsets:
- addresses:
  - ip: 192.168.50.75
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-scheduler
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-scheduler
    release: kube-prometheus-stack
subsets:
- addresses:
  - ip: 192.168.50.75
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-proxy
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-proxy
    release: kube-prometheus-stack
subsets:
- addresses:
  - ip: 192.168.50.75
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
