apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k3s-component-silence
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: k3s-component-silence
    rules:
    - alert: KubeSchedulerDown
      annotations:
        description: "Silenced for K3s: scheduler is embedded in K3s binary. To properly monitor, K3s server needs to be started with --kube-scheduler-arg='bind-address=0.0.0.0' and --kube-scheduler-arg='address=0.0.0.0'"
        summary: "K3s embedded scheduler component alert silenced"
      expr: absent(up{job="kube-scheduler"} == 1)
      for: 0m
      labels:
        severity: none
    - alert: KubeControllerManagerDown
      annotations:
        description: "Silenced for K3s: controller-manager is embedded in K3s binary. To properly monitor, K3s server needs to be started with --kube-controller-manager-arg='bind-address=0.0.0.0' and --kube-controller-manager-arg='address=0.0.0.0'"
        summary: "K3s embedded controller-manager component alert silenced"
      expr: absent(up{job="kube-controller-manager"} == 1)
      for: 0m
      labels:
        severity: none
    - alert: KubeProxyDown
      annotations:
        description: "Silenced for K3s: kube-proxy is embedded in K3s binary. To properly monitor, K3s server needs to be started with --kube-proxy-arg='metrics-bind-address=0.0.0.0'"
        summary: "K3s embedded kube-proxy component alert silenced"
      expr: absent(up{job="kube-proxy"} == 1)
      for: 0m
      labels:
        severity: none
    - alert: K3sServiceDown
      annotations:
        description: "Silenced for K3s: K3s metrics service is configured differently. To properly monitor, ensure the service has the correct port and labels."
        summary: "K3s service alert silenced"
      expr: absent(up{job="kubelet", metrics_path="/metrics"} == 1)
      for: 0m
      labels:
        severity: none
