apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-kube-controller-manager
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10257
    protocol: TCP
    targetPort: 10257
  selector:
    app: k3s-metrics-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-kube-scheduler
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-scheduler
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10259
    protocol: TCP
    targetPort: 10259
  selector:
    app: k3s-metrics-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-stack-kube-proxy
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-proxy
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    app: k3s-metrics-proxy
