apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-metrics
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-scheduler
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
    targetPort: 10251
  selector:
    node-role.kubernetes.io/control-plane: "true"
