apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager-metrics
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  selector:
    node-role.kubernetes.io/control-plane: "true"
