apiVersion: v1
kind: Service
metadata:
  name: kube-proxy-metrics
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-proxy
    release: kube-prometheus-stack
spec:
  ports:
  - name: http-metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    node-role.kubernetes.io/control-plane: "true"
