apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-backup-script
  namespace: bitwarden
data:
  backup-script.sh: |
    #!/bin/sh
    set -e

    # Create timestamp
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_NAME="vaultwarden-backup-${TIMESTAMP}"

    # NAS details
    NAS_USER="jannenasadm"
    NAS_HOST="192.168.50.25"
    NAS_PATH="/volume1/k3s_backups/vaultwarden"
    VAULTWARDEN_POD=$(kubectl get pod -n bitwarden -l app=bitwarden -o jsonpath='{.items[0].metadata.name}')

    # Get NAS password from environment
    NAS_PASS="${NAS_PASSWORD}"

    # Create temporary directory
    TMP_DIR=$(mktemp -d)
    echo "Created temporary directory: ${TMP_DIR}"

    # Create backup in pod
    echo "Creating backup in Vaultwarden pod..."
    kubectl exec -n bitwarden ${VAULTWARDEN_POD} -- bash -c "set -e && \
      cd /data && \
      tar czf /tmp/${BACKUP_NAME}.tar.gz db.sqlite3 attachments" || {
        echo "Failed to create backup in pod"
        rm -rf "${TMP_DIR}"
        exit 1
    }

    # Copy the backup from the pod
    echo "Copying backup from pod..."
    kubectl cp "bitwarden/${VAULTWARDEN_POD}:/tmp/${BACKUP_NAME}.tar.gz" "${TMP_DIR}/${BACKUP_NAME}.tar.gz" || {
        echo "Failed to copy backup from pod"
        rm -rf "${TMP_DIR}"
        exit 1
    }
    
    # Create backup directory on NAS
    echo "Creating backup directory on NAS..."
    export SSHPASS="${NAS_PASS}"
    sshpass -e ssh -o StrictHostKeyChecking=no -p 4711 "${NAS_USER}@${NAS_HOST}" "mkdir -p '${NAS_PATH}'" || {
        echo "Failed to create backup directory on NAS"
        rm -rf "${TMP_DIR}"
        exit 1
    }

    # Create SSH config
    echo "Creating SSH config..."
    SSH_CONFIG_DIR="/root/.ssh"
    SSH_CONFIG_FILE="${SSH_CONFIG_DIR}/config"
    mkdir -p "${SSH_CONFIG_DIR}"
    chmod 700 "${SSH_CONFIG_DIR}"
    cat > "${SSH_CONFIG_FILE}" << EOF
Host ${NAS_HOST}
    Port 4711
EOF
    chmod 600 "${SSH_CONFIG_FILE}"
    echo "Debug: SSH config created at ${SSH_CONFIG_FILE}"
    ls -la "${SSH_CONFIG_FILE}"
    cat "${SSH_CONFIG_FILE}"

    # Copy to NAS using sshpass
    echo "Copying backup to NAS..."
    echo "Debug: Using sshpass version:"
    sshpass -V
    echo "Debug: Command variables:"
    echo "TMP_DIR=${TMP_DIR}"
    echo "BACKUP_NAME=${BACKUP_NAME}"
    echo "NAS_USER=${NAS_USER}"
    echo "NAS_HOST=${NAS_HOST}"
    echo "NAS_PATH=${NAS_PATH}"
    echo "Debug: Attempting to copy file using scp..."
    export SSHPASS="${NAS_PASS}"
    sshpass -e scp -rv -O -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -F "${SSH_CONFIG_FILE}" "${TMP_DIR}/${BACKUP_NAME}.tar.gz" ${NAS_USER}@${NAS_HOST}:${NAS_PATH} || {
        echo "Failed to copy backup to NAS"
        echo "Debug: Testing SSH connection..."
        sshpass -e ssh -v -o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -p 4711 "${NAS_USER}@${NAS_HOST}" "ls -la \"${NAS_PATH}\""
        rm -rf "${TMP_DIR}"
        exit 1
    }

    # Clean up temporary directory
    echo "Backup completed successfully. Cleaning up..."
    rm -rf "${TMP_DIR}"

    # Clean up backup from pod
    echo "Cleaning up backup from pod..."
    kubectl exec -n bitwarden ${VAULTWARDEN_POD} -- rm -f "/tmp/${BACKUP_NAME}.tar.gz"

    # Keep only the 5 most recent backups on NAS
    echo "Cleaning up old backups on NAS..."
    sshpass -e ssh -o StrictHostKeyChecking=no -p 4711 "${NAS_USER}@${NAS_HOST}" "cd '${NAS_PATH}' && ls -t *.tar.gz | tail -n +6 | xargs -r rm --" || {
        echo "Warning: Failed to clean up old backups on NAS"
    }

    echo "Backup completed successfully!"
