apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitwarden-backup
  namespace: bitwarden
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitwarden-backup
  namespace: bitwarden
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitwarden-backup
  namespace: bitwarden
subjects:
- kind: ServiceAccount
  name: bitwarden-backup
  namespace: bitwarden
roleRef:
  kind: Role
  name: bitwarden-backup
  apiGroup: rbac.authorization.k8s.io
