apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-backup-script
  namespace: bitwarden
data:
  backup-script.sh: |
    #!/bin/sh
    set -e

    # Get the Vaultwarden pod name
    VAULTWARDEN_POD=$(kubectl get pod -n bitwarden -l app=bitwarden -o jsonpath='{.items[0].metadata.name}')
    
    # Create a temporary directory for the backup
    BACKUP_DIR="/tmp/vaultwarden-backup"
    mkdir -p $BACKUP_DIR
    
    echo "Creating backup from pod $VAULTWARDEN_POD..."
    
    # Copy SQLite database and attachments from the pod
    kubectl cp bitwarden/$VAULTWARDEN_POD:/data/db.sqlite3 $BACKUP_DIR/db.sqlite3
    kubectl cp bitwarden/$VAULTWARDEN_POD:/data/attachments $BACKUP_DIR/attachments
    
    # Create timestamped archive
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="vaultwarden_backup_$TIMESTAMP.tar.gz"
    
    cd /tmp
    tar czf $BACKUP_FILE vaultwarden-backup/
    
    # Set up SSH config
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    cp /ssh-config/config ~/.ssh/
    chmod 600 ~/.ssh/config

    # Upload to NAS
    echo "Uploading backup to NAS..."
    export SSHPASS="$NAS_PASSWORD"
    sshpass -e rsync -e "ssh -o StrictHostKeyChecking=no" $BACKUP_FILE jannenasadm@192.168.50.25:/volume1/k3s_backups/vaultwarden/
    
    # Cleanup
    rm -rf $BACKUP_DIR $BACKUP_FILE
    
    echo "Backup completed successfully!"
