apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
data: 
  # SMTP Configuration for email verification and 2FA
  SMTP_HOST: 'smtp-relay.brevo.com'
  SMTP_FROM: 'jannegpriv@gmail.com'
  SMTP_FROM_NAME: 'Vaultwarden'
  SMTP_PORT: '587'
  SMTP_SECURITY: 'starttls'
  SMTP_TIMEOUT: '15'
  SMTP_AUTH_MECHANISM: 'Login'
  SMTP_DEBUG: 'true'
  
  # Domain and Web Configuration
  DOMAIN: 'https://vaultwarden.k3s.nu'
  WEBSOCKET_ENABLED: 'true'
  WEB_VAULT_ENABLED: 'true'
  ROCKET_PORT: '80'
  ROCKET_WORKERS: '10'
  ROCKET_ADDRESS: '0.0.0.0'
  ROCKET_LOG: 'debug'
  ROCKET_CLI_COLORS: 'false'
  IP_HEADER: 'X-Forwarded-For'
  PROXY_ENABLED: 'true'
  PROXY_PROTOCOL_ENABLED: 'true'
  
  # Security Settings
  SIGNUPS_ALLOWED: 'false'  # Disabled after initial admin account creation
  INVITATIONS_ALLOWED: 'true'  # Allow invites even when signups are disabled
  SHOW_PASSWORD_HINT: 'false'
  EMERGENCY_ACCESS_ALLOWED: 'true'
  
  # 2FA Settings
  TWO_FACTOR_AUTHENTICATION_ENABLED: 'true'
  DUO_ENABLED: 'true'  # Enable Duo 2FA support
  YUBIKEY_ENABLED: 'true'  # Enable YubiKey OTP
  
  # Email 2FA Settings
  EMAIL_2FA_ENABLED: 'true'
  EMAIL_TOKEN_SIZE: '8'  # Length of email 2FA token
  EMAIL_EXPIRATION_TIME: '600'  # Email token validity in seconds (10 minutes)
  
  # Storage and Logging
  DATA_FOLDER: '/data'
  LOG_FILE: '/data/bitwarden.log'
  LOG_LEVEL: 'warn'  # Logging level: trace, debug, info, warn, error
  
  # Password Policy
  PASSWORD_ITERATIONS: '600000'  # PBKDF2 iterations for password hashing
  PASSWORD_HINTS_ALLOWED: 'false'  # Disable password hints for security
