apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bitwarden-https
  namespace: bitwarden
spec:
  headers:
    customResponseHeaders:
      Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "vaultwarden.k3s.nu"
      X-Forwarded-For: ""
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh moz-extension://*"
    customFrameOptionsValue: "SAMEORIGIN"
    referrerPolicy: "same-origin"
