apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bitwarden-https
  namespace: bitwarden
spec:
  headers:
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    customRequestHeaders:
      X-Forwarded-Proto: "https"
