apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-cert
  namespace: bitwarden
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - vaultwarden.k3s.nu
