apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
data: 
  SMTP_HOST: 'smtp-relay.sendinblue.com'
  SMTP_FROM: 'jannegpriv@smtp-relay.sendinblue.com'
  SMTP_PORT: '587'
  SMTP_SSL: 'true'
  WEBSOCKET_ENABLED: 'true'
  DATA_FOLDER: '/data'
  DOMAIN: 'https://k3s-bitwarden.example.org'
  ROCKET_WORKERS: '10'
  SHOW_PASSWORD_HINT: 'false'
  WEB_VAULT_ENABLED: 'true'
  ROCKET_PORT: '8080'
  SIGNUPS_ALLOWED: 'true'
  INVITATIONS_ALLOWED: 'true'
  LOG_FILE: "/data/bitwarden.log"
