kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: bitwarden
  name: bitwarden-data-claim
  namespace: bitwarden
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
