apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden
  namespace: bitwarden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: vaultwarden.k3s.nu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bitwarden
            port:
              name: bitwarden-http
  tls:
  - hosts:
    - vaultwarden.k3s.nu
    secretName: vaultwarden-k3s-nu-tls
