apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  selector:
    app: bitwarden
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30180
    - name: websocket
      protocol: TCP
      port: 3012
      targetPort: 3012
