apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-k3s-nu
  namespace: bitwarden
spec:
  secretName: vaultwarden-k3s-nu-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - vaultwarden.k3s.nu
