apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - bitwarden-claims.yaml
  - bitwarden-config.yaml
  - bitwarden-secrets.yaml
  - bitwarden-rbac.yaml
  - bitwarden-statefulset.yaml
  - bitwarden-service.yaml
  - bitwarden-ingress.yaml
  - bitwarden-middleware.yaml
  - certificate.yaml
  - backup-rbac.yaml
  - backup-script-configmap.yaml
  - backup-cronjob.yaml
  - ssh-config-configmap.yaml
