apiVersion: v1
kind: ConfigMap
metadata:
  name: k3s-component-config
  namespace: kube-system
data:
  config.yaml: |
    kube-controller-manager-arg:
      - "bind-address=0.0.0.0"
    kube-proxy-arg:
      - "metrics-bind-address=0.0.0.0"
    kube-scheduler-arg:
      - "bind-address=0.0.0.0"
