{
 "title": "K3s Cluster Logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Error Logs by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({namespace=~\".+\"} |~ \"error|Error|ERROR\" [$__interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"$search\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Rook-Ceph Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"rook-ceph\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "OpenHAB Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"openhab\"} |~ \"$search\""
    }
   ]
  }
 ]
}