apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.loki.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: prometheus
              matcherRegex: "instance=([^,\\s]+)"
              name: instance
              url: '$${__value.raw}'
            - datasourceUid: prometheus
              matcherRegex: "pod=([^,\\s]+)"
              name: pod
              url: '$${__value.raw}'
        editable: true
