apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 30m
  chart:
    spec:
      chart: n8n
      version: "0.25.2"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
      interval: 12h
  values:
    image:
      repository: n8nio/n8n
      tag: "1.70.1"
    
    persistence:
      enabled: true
      existingClaim: n8n-data
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    
    config:
      generic:
        timezone: Europe/Stockholm
      executions:
        pruneData: "true"
        pruneDataMaxAge: 168  # 7 days in hours
    
    extraEnv:
      - name: N8N_PROTOCOL
        value: "http"
      - name: N8N_HOST
        value: "n8n.local"
      - name: WEBHOOK_URL
        value: "http://n8n.local/"
      - name: N8N_ENCRYPTION_KEY
        valueFrom:
          secretKeyRef:
            name: n8n-secrets
            key: encryption-key
